### ISSUE TITLE
Add ruff

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac#1030]
It's nice and it's getting a lot of adoption: https://github.com/charliermarsh/ruff. It should be added to CI and **pre-commit**.

**Comment by philvarner** [comment]
🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺 🐕‍🦺
