### ISSUE TITLE
Extensions should coerce values to correct type

### ISSUE THREAD

**Issue by jsignell** [stac-utils/pystac#1044]
Specifically non-null values in "proj:epsg" and "proj:shape" should be coerced to int. Ideally this should happen on the `properties` field itself rather than only when directly getting the prop from the extension class

## Context
I was debugging an issue on VEDA where epsg was being read as a float and causing some issues.

```python
import pystac
from pystac.extensions.projection import ProjectionExtension

item = pystac.Item.from_file("https://staging-stac.delta-backend.com/collections/nceo_africa_2017/items/AGB_map_2017v0m_COG")
print(ProjectionExtension.has_extension(item))  # False
print(item.properties["proj:epsg"])  # 4326.0
```

I decided that maybe there was a mismatch between the STAC version and the extension version, so I pulled the file locally (using `wget`) and changed proj ext schema version from v1.0.0 to v1.1.0

```python
import pystac
from pystac.extensions.projection import ProjectionExtension

item = pystac.Item.from_file("AGB_map_2017v0m_COG")
print(ProjectionExtension.has_extension(item))  # True
print(item.properties["proj:epsg"])  # 4326.0
print(ProjectionExtension.ext(item).epsg)  # 4326.0
```

This time the proj ext is understood ~, but in the process of pulling the file all my int fields were converted to floats. I _think_ this is because json doesn't really understand the difference between ints and floats.~ but since my STAC entry contains floats rather than ints, the value is always a float. Even when getting it directly from the  extension class.

**Comment by jsignell** [comment]
So the part about `wget`ting the file converting from int to float is probably incorrect.

**Comment by vincentsarago** [comment]
#### using python https
```python
import httpx
r = httpx.get("https://staging-stac.delta-backend.com/collections/nceo_africa_2017/items/AGB_map_2017v0m_COG")
r.json()["properties"]["proj:epsg"]
>>>  4326.0
```

#### using curl
```bash
curl https://staging-stac.delta-backend.com/collections/nceo_africa_2017/items/AGB_map_2017v0m_COG   
{...,"proj:epsg":4326.0,...}%  
```

When I use `jq` it does coerce the float to in 

```bash
curl https://staging-stac.delta-backend.com/collections/nceo_africa_2017/items/AGB_map_2017v0m_COG | jq -c '.properties."proj:epsg"'
4326
```

**Comment by jsignell** [comment]
json validation does not catch this either because in json schema numbers with a trailing .0 are considered valid integers: https://json-schema.org/understanding-json-schema/reference/numeric.html

**Comment by jsignell** [comment]
Just to make this explicit. I think there are two very different approaches available:

1) In the top level `json_loads` coerce all floats that end with `.0` to ints. This is at the highest level and does not involve any changes to how extensions work or any per-extension changes. 
2) Make type coercion the responsibility of the extensions. If we choose this approach we will need to do special deserialization per-extension on each pystac object to ensure that the correct coercion is applied.

**Comment by gadomski** [comment]
> Make type coercion the responsibility of the extensions. If we choose this approach we will need to do special deserialization per-extension on each pystac object to ensure that the correct coercion is applied.

My instinct is option 2, option 1 feels a little to magical to me.

Typing and (de)serialization is a recurring problem in PySTAC (e.g. https://github.com/stac-utils/pystac/issues/1047), and I think forcing extensions to define the behavior that they want is the best call -- e.g. for projection, you may want to error if `epsg` has a fractional part, but another extension might be ok with a round/truncate to get from a `float` to an `int`.

**Comment by jsignell** [comment]
I agree that using a dedicated library seems like a better fit. Do you think we should close this since the preferred approach is captured in https://github.com/stac-utils/pystac/issues/1092? FWIW, VEDA is correcting the values within the pgstac database, and there are conversations going on about changing the type of `proj:epsg` to be string rather than int, which would also fix the original issue that I was running into.

**Comment by gadomski** [comment]
> Do you think we should close this since the preferred approach is captured in https://github.com/stac-utils/pystac/issues/1092?

Sure. I think an issue specifically focused on a single extension (e.g. "Proj extension should fail if EPSG is not an integer") would be more actionable.
