### ISSUE TITLE
Item __geo_interface__ returns the wrong represenation

### ISSUE THREAD

**Issue by philvarner** [stac-utils/pystac#1048]
The Item __geo_interface__ is currently:

```
    @property
    def __geo_interface__(self) -> Optional[Dict[str, Any]]:
        """Returns this item's geometry.

        https://gist.github.com/sgillies/2217756

        Returns:
            Dict[str, Any]: The Item's geometry
        """
        return deepcopy(self.geometry)
```

However, this should be returning a JSON-typed dict of a Feature for the Item, rather than the Item's geometry.

**Comment by gadomski** [comment]
Ah, _that's_ why I made it return `geometry` initially. I thought I had some reason, but I couldn't remember it.

While it might be considered out-of-scope for **shapely** to support GeoJSON (and not just geometries), it would make my life a lot easier ... I've found that you sometimes have to do manual GeoJSON work to go from a dict to something **shapely** likes: https://github.com/gadomski/antimeridian/blob/5f9f2d35657a9ecff88575339ef1e17c25d0fdc7/src/antimeridian/_implementation.py#L56-L86

**Comment by jorisvandenbossche** [comment]
> While it might be considered out-of-scope for **shapely** to support GeoJSON (and not just geometries)

Shapely (>=2) actually supports GeoJSON, through `shapely.from_geojson`(https://shapely.readthedocs.io/en/stable/reference/shapely.from_geojson.html), but that is assuming your start from a GeoJSON string (not python dict). 



> I've found that you sometimes have to do manual GeoJSON work to go from a dict to something **shapely** likes:

If there are specific cases where `shapely.geometry.shape(..)` does not support something that resembles valid GeoJSON, you are certainly welcome to give some examples / bring those up to shapely (it might be in scope to fix, I don't know by heart what are exactly the differences between GeoJSON and `__geo_interface__`)
