### ISSUE TITLE
validate_has_extension is a bad name for a method that has can modify the object

### ISSUE THREAD

**Issue by philvarner** [stac-utils/pystac#1061]
validate_has_extension can modify the object if add_if_missing is set to True. `validate` is usually used only for non-mutating methods, e.g., ones that just validate the state of something without changing it. Since this is the case, a better name for this method would be `ensure_has_extension`.

**Comment by gadomski** [comment]
Moving this to 1.9 milestone because we can deprecate `validate_has_extension` instead of removing.

**Comment by gadomski** [comment]
Closed by #1248
