### ISSUE TITLE
Add jinja2 as an extra for accessing formatted html representation of Collections and Items

### ISSUE THREAD

**Issue by pjhartzell** [stac-utils/pystac#1082]
You only get access to the formatted Collection and Item html provided by `_repr_html_ ()` when **jinja2** is installed. This does not appear to be noted anywhere.

I think **jinja2** should be included in the `setup.py` `extras_require` dictionary and noted in the installation docs in the [Dependencies section](https://pystac.readthedocs.io/en/latest/installation.html#dependencies).

**Comment by jsignell** [comment]
Given the transition to pyproject.toml there isn't an `extra_require` anymore but there are specific "project.optional_dependencies". So I guess we could create a new one called `display` or something? Also this would be closed by #1130 if people like that idea.
