### ISSUE TITLE
Arbitrary saving location of child catalogs

### ISSUE THREAD

**Issue by constantinius** [stac-utils/pystac#1116]
It is hard to control the actual storage location of child catalogs when they are child of more than one catalog. Consider the following example:

```python
import pystac

root = pystac.Catalog("root", "root")
left = pystac.Catalog("left", "left")
right = pystac.Catalog("right", "right")

root.add_child(left)
root.add_child(right)

child = pystac.Catalog("child", "child")

left.add_child(child)
right.add_child(child)

root.normalize_and_save("out_test", pystac.CatalogType.ABSOLUTE_PUBLISHED)
```

Whether the "child" catalog is saved under `left/child` or `right/child` depends on the order "left" and "right" are added to "root" (`right/child` in this case, as "right" was added after "left").

---

Additionally, when I change the order of the catalog addition:
```python
root.add_child(right)
root.add_child(left)

# ...

left.add_child(child)
right.add_child(child)
```

Then there is no parent link from "child" to "right" at all, even when this should be the case as the `add_child` on "right" was called last:

```json
{
  "type": "Catalog",
  "id": "child",
  "stac_version": "1.0.0",
  "description": "child",
  "links": [
    {
      "rel": "root",
      "href": "/out_test/catalog.json",
      "type": "application/json"
    },
    {
      "rel": "parent",
      "href": "/out_test/left/catalog.json",
      "type": "application/json"
    },
    {
      "rel": "self",
      "href": "/out_test/left/child/catalog.json",
      "type": "application/json"
    }
  ],
  "stac_extensions": []
}
```

**Comment by m-mohr** [comment]
Related: https://github.com/radiantearth/stac-spec/issues/1230

**Comment by m-mohr** [comment]
PR is at #1117

**Comment by m-mohr** [comment]
Sorry, I'm reopening here because #1117 actually doesn't fully solve the issue. It helps with the parent links, but the storage location is still showing unexpected results.

**Comment by m-mohr** [comment]
I've looked into the code a bit and it looks difficult ;-) Some findings:
- resolve_stac_object overrides the parent that we have carefully set before (from left to right)
- In normalize_href it sets the self links for a single catalog first to left and then to right, which decides the storage location. It doesn't take the parent into account, which I think it should.

**Comment by gadomski** [comment]
```python
left.add_child(child)
right.add_child(child, keep_parent=True)
```

I'm starting to wonder if we're outrunning the spec here. My preferred solution would be to disallow multiple parents (https://github.com/radiantearth/stac-spec/issues/1230), and then throw an error on the second `add_child` call (obviously, we'd remove the just-added `keep_parent` argument of `add_child`).

**Comment by m-mohr** [comment]
I don't think we do. Isn't that exactly what browsable encourages (in the API world)? And isn't it also a common usecase do combine multiple data sources into one catalog?

**Comment by gadomski** [comment]
It seems strange to me to have a child link in one direction, but no parent link back. That feels very un-browseable. But maybe I'm misunderstanding the use case.

```mermaid
---
title: This seems bad
---
flowchart TD
    A <-- child+parent --> C
    B -- child --> C
```

**Comment by m-mohr** [comment]
Yes, but then we are looking at multiple parents again, see https://github.com/radiantearth/stac-spec/issues/1230.

I think, the example mentioned in https://github.com/radiantearth/stac-spec/issues/1230#issuecomment-1544079321 is a very valid use case for a static catalog as it makes the data easier to find by users (imaging hundreds of collections) by providing different access paths. That's exactly what @cholmes always tried to encourage with Browsable. In an API it's simpler of course, as you can update the parent depending on where you are coming from, but in static it's impossible. And in an API you may also argue that it's strange to have an item with an id have different (parent) links depending on the access path. You won't have one source of truth then. So if you are saying that this is invalid, we'd basically say Browsable should be removed as an extension as this won't work then (assuming we don't want to duplicate data).

**Comment by gadomski** [comment]
> So if you are saying that this is invalid, we'd basically say Browsable should be removed as an extension as this won't work then (assuming we don't want to duplicate data).

Not saying this is invalid, just saying that it scans strange _to me_. But I see the use case and it seems reasonable enough.

> The structure for us is set, but maybe PySTAC is not the right tool for us?

Nah, it _should_ be simple enough to add a child w/o setting the `parent` link. I'll take another look at your draft PR and see if I can't untangle things.
