### ISSUE TITLE
Additional Media Types (KML)

### ISSUE THREAD

**Issue by wildintellect** [stac-utils/pystac#1127]
There are some fairly common and standard(OGC) MediaTypes not current listed in https://github.com/stac-utils/pystac/blob/main/pystac/media_type.py
In particular KML and KMZ which seem to be common sidecar files on a lot of Collections.

I can make a PR for 
```
KML = "application/vnd.google-earth.kml+xml"
```

Opened this ticket to track, and solicit if we're missing some other obvious candidates?

**Comment by gadomski** [comment]
Closed by #1151
