### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac#1148]
We've had a de-facto policy to follow **numpy**'s deprecation policy, https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table, where Python 3.8 support was dropped on 2023-04-14.

We should probably also update our docs to explicitly state that we're following **numpy**'s deprecation policy.

Once this issue is closed, the same should be done for:
- [ ] **pystac-client**
- [ ] **stactools**

**Comment by jsignell** [comment]
:fire: :fire: maybe we can run pyupgrade on the code while we are at it to make sure we are taking advantage of the latest and greatest features.

**Comment by gadomski** [comment]
> We should probably also update our docs to explicitly state that we're following numpy's deprecation policy.

Whoops, we already do this: https://github.com/stac-utils/pystac/blob/9c323c4e9a2e1b27a87eefce23b9c49d0fb3298c/docs/installation.rst?plain=1#L30-L34

> 🔥 🔥 maybe we can run pyupgrade on the code while we are at it to make sure we are taking advantage of the latest and greatest features.

I've opened a new issue to track this (https://github.com/stac-utils/pystac/issues/1235), since I want to separate the "remove 3.8" PR from the "run pyupgrade" PR (since that'll be noisy).
