### ISSUE TITLE
Don't use `RefResolver`

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac#1186]
As of **jsonschema** v4.18, `RefResolver` is deprecated:

```
DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
```

This issue is to track the need to update to The New Way.

**Comment by gadomski** [comment]
Thanks for the report Vincent! I wonder if we should ceil **jsonschema** below v4.18 for the time being? What's your sense of how broken things are over there?

**Comment by vincentsarago** [comment]
Yep that's what I did in #1189 😅

**Comment by gadomski** [comment]
Yup, agreed. I'll open a PR to fix.

**Comment by gadomski** [comment]
#1189 is released in [v1.8.2](https://github.com/stac-utils/pystac/releases/tag/v1.8.2).

**Comment by jsignell** [comment]
I'm going to look into this a bit today to see if the timing is right to pick it up

**Comment by 2320sharon** [comment]
Hi @jsignell, thank you for addressing this issue. It's blocking the resolution of https://github.com/stac-utils/pystac/issues/1214, which is affecting Jupyter Lab in downstream applications. We truly appreciate your efforts!
