### ISSUE TITLE
Validate STAC links for single dict

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/pystac#1205]
As far as I understand, validate_all implicitly validates whether the STAC links (item, child) are valid (i.e. the href exists).
It would be great if this small feature would also be available (via a flag/parameter) in the validation for a single object/dict.

**Comment by jamesfisher-gis** [comment]
Hey @m-mohr,

Does the `recursive` parameter in [validate_all](https://pystac.readthedocs.io/en/latest/_modules/pystac/catalog.html#Catalog.validate_all) address your issue?

For example:
```python
import pystac

catalog_file = r"https://raw.githubusercontent.com/stac-utils/pystac/main/tests/data-files/catalogs/label_catalog-v0.8.1/catalog.json"
catalog = pystac.Catalog.from_file(catalog_file)
```

```python
catalog.validate_all()
>>> 62
```

```python
catalog.validate_all(recursive=False)
>>> 0
```

**Comment by m-mohr** [comment]
I don't think so. The question is not related to recursion, more to be able to check whether link hrefs actually exist.

**Comment by gadomski** [comment]
> I don't think so. The question is not related to recursion, more to be able to check whether link hrefs actually exist.

In `Catalog.validate_all`, all item and child links are checked and validated regardless of the value of `recursive`:

https://github.com/stac-utils/pystac/blob/9c323c4e9a2e1b27a87eefce23b9c49d0fb3298c/pystac/catalog.py#L1058-L1069

So `Catalog.validate_all(recursive=False)` and `Catalog.validate_all(recursive=False)` will check all STAC links on the Catalog/Collection without recursing into the children and validating those links.

**Comment by m-mohr** [comment]
But the issue is about validate, not validate_all.

**Comment by gadomski** [comment]
> But the issue is about validate, not validate_all.

😕 I _think_ we currently allow all the possible cases via `validate` and `validate_all`:

- `Catalog.validate()` does not read or validate links
- `Catalog.validate_all(recursive=False)` reads and validates links, but does not do the same for children
- `Catalog.validate_all(recursive=True)` reads and validates links, and does the same for children

Is there another behavior that I'm missing?

**Comment by m-mohr** [comment]
Oh, I see. You were saying I should use validate_all(recursive=False) instead of validate. Will try...
