### ISSUE TITLE
Regression: Adjusting Assets does not have an effect

### ISSUE THREAD

**Issue by constantinius** [stac-utils/pystac#1209]
In the [`stactools-datacube`](https://github.com/stactools-packages/datacube/blob/main/src/stactools/datacube/stac.py#L323-L324) package we extend an Item like this:

```python
    asset = item.get_assets()[asset_name]
    datacube = extend_asset(item, asset, rtol)
```

This used to work, but with `pystac==1.8.3` this results in an empty asset. When explicitly re-adding the asset it works again:

```python
    asset = item.get_assets()[asset_name]
    datacube = extend_asset(item, asset)
    item.add_asset(asset_name, asset)
```
Is it now required to re-add the asset to the item to trigger the update?

**Comment by gadomski** [comment]
I'd access the assets dictionary directly if you want to modify it:

```python
asset = item.assets[asset_name]
```

The behavior of `get_assets` was intentionally changed in https://github.com/stac-utils/pystac/pull/1087.

**Comment by constantinius** [comment]
Thanks @gadomski, will fix this in stactools-datacube
