### ISSUE TITLE
Deprecate the label extension

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac#1249]
It is currently unmaintained, in "pilot" maturity, and has significant issues with its current implementation. We should deprecate the extension class in this repo, and remove its usage from any test files.

**Comment by fmariv** [comment]
Hi, I would like to revisit this topic and discuss removing the deprecated status from the extension label. At @earthpulse we use this extension for our [labeling tool](https://pypi.org/project/scaneo/), and the [EOTDL](https://www.eotdl.com/), a project funded by ESA which aims to be a Training Dataset repository, strongly relies on this extension. There is some fear in the community that this extension is deprecated, so it would be good to talk about this topic.
