### ISSUE TITLE
SpatialExtent value type checking allows creation of invalid Collections

### ISSUE THREAD

**Issue by bmcandr** [stac-utils/pystac#1267]
The type hints in the class constructor of `SpatialExtent` indicate that either `List[float] | List[List[float]]` are expected:

https://github.com/stac-utils/pystac/blob/ed810362f342aa2bed5e03f3d7398460977431c4/pystac/collection.py#L74

But there is minimal validation around this which allows for the creation `Collection`s with malformed `SpatialExtent`s:

https://github.com/stac-utils/pystac/blob/ed810362f342aa2bed5e03f3d7398460977431c4/pystac/collection.py#L77-L82

For example, a bbox containing a list of integers will not be cast to a nested list because the `isinstance(bboxes[0], float)` type check fails. While we should be obeying the type hints, we have inadvertently created Collections that fail validation this way.

The STAC spec indicates the type for bbox is [[[number]]](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#spatial-extent-object) which is either an [integer or float](https://json-schema.org/understanding-json-schema/reference/numeric#number) so it seems like the "validation" here _should_ properly handle a list of integers as well.

Is there any appetite for more robust type-checking here? Properly handle float/int, fail for other types? If so, I'm happy to put together a merge request!

**Comment by bmcandr** [comment]
Actually, looks like this is a version issue on my end. Closing.

**Comment by bmcandr** [comment]
Reopened after reading a bit more about `typing.cast`. I understand that it is used to satisfy type-checkers and _does not actually alter the value passed into it_.

>`typing.cast(typ, val)`
>Cast a value to a type.
>
>[**This returns the value unchanged.** To the type checker this signals that the return value has the designated type, but at runtime we intentionally don’t check anything (we want this to be as fast as possible).](https://docs.python.org/3.9/library/typing.html#typing.cast)

However, the comment in the snippet above suggests the logic is intended to "transform" the `bboxes` into a list of bboxes if not supplied in that format. Is the code truth or the comment? If the latter, then I think my comment still stands.

**Comment by jsignell** [comment]
Yes casting is pretty confusing. I agree that it seems like the commenter intended to alter the type of the input. More robust coercion to the correct type would be great. PRs welcome!
