### ISSUE TITLE
Deprecation notice in docs for Catalog.get_all_items() includes extra parentheses

### ISSUE THREAD

**Issue by tylere** [stac-utils/pystac#1314]
In the [pystac docs](https://pystac.readthedocs.io/en/stable/api/catalog.html
) the docs for Catalog.get_all_items() have an extra set of parentheses in the deprecation notice.

![Screenshot 2024-03-06 at 2 46 30 PM](https://github.com/stac-utils/pystac/assets/92862/7e785a36-feca-479f-ac6b-0a5df3029d94)

The docstring for the method looks ok though, so I am not sure what is going on...
https://github.com/stac-utils/pystac/blob/b3edc53cb29ac563c5b141dd6739b86ff68a3eef/pystac/catalog.py#L603

**Comment by jsignell** [comment]
Thanks for reporting! My bet is that `:meth:` is doing something sneaky and adding the parens
