### ISSUE TITLE
Repair automated release process

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac#1326]
The v1.10.0 release to PyPI [failed](https://github.com/stac-utils/pystac/actions/runs/8480760122). I _think_ that the token we're using (via Github Actions secrets) has expired, but I can't be sure b/c I don't have access to the **stac-utils** PyPI account. I'm going to bring up the topic at the next regular STAC community meeting and we can come up with a plan to future-proof our release/maintenance process there. I expect that whatever we come up with will apply to more than just **pystac** (e.g. **pystac-client** at least should use a similar process).

**Comment by ghidalgo3** [comment]
@gadomski do you have any updates to share about this? I would like to use some unreleased changes (specifically the newest media types!) and I need to pull from PyPI instead of GitHub.

**Comment by gadomski** [comment]
We don't have a planned release date for our next MINOR release (v1.11) yet ... I should probably page through https://github.com/stac-utils/pystac/milestone/37 and see which of those can be done w/o breaking and get those in. I'll do my best to get on that this next week, and then hopefully get a v1.11 out shortly after. Thanks for your patience 🙇🏼
