### ISSUE TITLE
Broken search on docs

### ISSUE THREAD

**Issue by soxofaan** [stac-utils/pystac#1349]
- go to https://pystac.readthedocs.io/en/stable/
- triggering search widget does not work: 
   - clicking it in top right does nothing
   - shortcut ctrl+k does nothing

In wedev console I see these errors being triggered from attempts above
```
Uncaught TypeError: null has no properties
    c pydata-sphinx-theme.js:196
    i pydata-sphinx-theme.js:211
    937 pydata-sphinx-theme.js:295
    937 pydata-sphinx-theme.js:294
    r mixin.js:12
    937 pydata-sphinx-theme.js:582
    a async module:49
    937 pydata-sphinx-theme.js:1
    Webpack 3
pydata-sphinx-theme.js:196:22
```

**Comment by soxofaan** [comment]
note that search does work from deeper pages, e.g. https://pystac.readthedocs.io/en/stable/installation.html, https://pystac.readthedocs.io/en/stable/quickstart.html, ...

**Comment by jsignell** [comment]
This really confused me as well until I realized that the search bar is already on the page:

![image](https://github.com/user-attachments/assets/320e71dd-da19-4ba5-8764-b65117449060)

This behavior feels confusing to me so I will open a PR to change to the way it works everywhere else: 
![image](https://github.com/user-attachments/assets/ae8557be-7a60-437c-b56c-c11bc307bed2)
