### ISSUE TITLE
Configuring RetryStacIO

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/pystac#1353]
I'm using **pystac-client** to search for STAC items and have configured the retry behavior as described in the [documentation](https://pystac-client.readthedocs.io/en/stable/usage.html#configuring-retry-behavior). After finding the items, I download the assets using **stac-asset**.  However, sometimes I'm encountering this error:
```
Could not read uri ...
```
This error originates from [this section of the pystac code](https://github.com/stac-utils/pystac/blob/dc4d9afb533f7d2d00a59350d14a209bba72558d/pystac/stac_io.py#L303).

It appears that there is a `RetryStacIO` class, which seems to be independent of the retry behavior configured at the **pystac-client** level. My question is: How can I configure `RetryStacIO` in the same manner as it is done for **pystac-client**?

Thank you for your assistance.

**Comment by drnextgis** [comment]
Apparently something like this should work:

```python
from pystac.stac_io import RetryStacIO, StacIO
StacIO.set_default(RetryStacIO)
```

But still not quite clear what is the proper way of re-using an existing Retry object:
```
from urllib3 import Retry

retry = Retry(
    total=5,
    backoff_factor=1,
    status_forcelist=[502, 503, 504],
    allowed_methods=None,
)
```

Additionally, the retry property is defined both at the class level and within the constructor in `RetryStacIO`, which is a bit confusing.

**Comment by gadomski** [comment]
Your examples make sense, do they seem to work? `StacIO` is generally a bit wonky and confusing -- there's some documentation in https://pystac.readthedocs.io/en/stable/concepts.html#i-o-in-pystac that is more-or-less what you've demonstrated above.

> Additionally, the retry property is defined both at the class level and within the constructor in RetryStacIO, which is a bit confusing.

I've opened #1358 to address this.
