### ISSUE TITLE
`get_all_collections` only goes one level deeper

### ISSUE THREAD

**Issue by 387809109** [stac-utils/pystac#1360]
I was trying to call `get_all_collections` to recursively get all collections within a root catalog. It turned out that only collections of the root catalog and its direct children are returned.

Looking at the code https://github.com/stac-utils/pystac/blob/ff67de3e4413422a417939bf49aa5b14428db35c/pystac/catalog.py#L455
```
def get_all_collections(self) -> Iterable[Collection]:
    """Get all collections from this catalog and all subcatalogs. Will traverse
    any subcatalogs recursively."""
    yield from self.get_collections()
    for child in self.get_children():
        yield from child.get_collections()
```
It seems that it's expected to only return collections from self and children.

Is it intentional or a bug?

**Comment by jsignell** [comment]
That looks like a bug to me. I think that second yield should be `child.get_all_collections()`. I can open a PR now.
