### ISSUE TITLE
str/repr mixup in StringEnum?

### ISSUE THREAD

**Issue by soxofaan** [stac-utils/pystac#1369]
https://github.com/stac-utils/pystac/blob/630116c7c31639818b1342c9d2f4231a14dca4f0/pystac/utils.py#L78-L83

Is it intentional to return `str(self.value)` instead of  `repr(self.value)` here?

**Comment by jsignell** [comment]
Yeah that seems fine to switch it to `repr` not sure if it would ever make a difference since by definition the value will always be a string, but I don't see a downside so please open a PR if you feel it's an improvement.
