### ISSUE TITLE
Query USGS for DEM data

### ISSUE THREAD

**Issue by normanb** [stac-utils/pystac#1481]
I am using the following 1M DEM catalog - https://portal.opentopography.org/stac/USGS1m_catalog.json

It has a typo in the JSON file (a double comma), removing this typo as saving to a local file I query as follows; 

```
    root_catalog = Catalog.from_file(src)
    collections = list(root_catalog.get_collections())
```

Which gives the error 

```
pystac.errors.STACTypeError: JSON (id = OT.012021.4269.3) does not represent a Catalog instance.
```

**Comment by gadomski** [comment]
Yup, that's correct. The STAC value at https://portal.opentopography.org//stac//USGS1m//raster_catalog.json, with an id of `OTNED.012021.4269.3`, is a (v1.0.0-beta.2) STAC Item, not a catalog. However, the link from the root catalog is a `child` link, indicating that it should be a Catalog or a Collection.
