### ISSUE TITLE
Enable automatically adjusting the STAC version in documentation

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#149]
In the sphinx documentation there are a lot of links that use the STAC version explicitly in the URL. Each time PySTAC gets upgraded there's a process of hunting down and changing each of these links.

For the tutorial links, however, it uses the `extlinks` to use a specific git branch to create a link with a programmatically formatted string. A similar approach could be used to anywhere that uses a STAC version in a link.

The goal of this issue is to use an `extlinks` approach to anywhere in the docs that has a link with a specific STAC or PySTAC version in order to make future upgrades easier.

**Comment by aazuspan** [comment]
Was this resolved by 9e9b4b19a8282a3f40903a7212bee635fe061eee? At a glance, I didn't see any hard-coded versions left in the docs.

**Comment by gadomski** [comment]
Looking through, there's a couple of links in the notebooks that still need fixing, e.g. in `creating-a-landsat-stac.ipynb` and `quickstart.ipynb`. Not sure if `extlinks` is necessary, or if we can just reference the `master` branch or `latest` version of docs.

**Comment by jsignell** [comment]
I was just taking a look at this and it looks like the landsat 8 collection 1 data that is referenced in the `create-a-landsat-stac.ipynb` is no longer available: https://www.usgs.gov/landsat-missions/landsat-collection-1. From poking around it seems like the landsat collection 2 data is all in requester pays buckets?

**Comment by gadomski** [comment]
> From poking around it seems like the landsat collection 2 data is all in requester pays buckets?

I believe that's true. We could update it to use the Planetary Computer (which is free access)?
