### ISSUE TITLE
Improve unit tests

### ISSUE THREAD

**Issue by simonkassel** [stac-utils/pystac#155]
We would like to improve unit tests in some portions of the code base. Here are some locations that could use additional testing. Feel free to not limit yourself to these examples.

- Test validation on invalid stac examples https://github.com/azavea/pystac/blob/develop/tests/validation/test_validate.py
- `can_extend` method of base extension object https://github.com/azavea/pystac/blob/2605f271da7e9e267cf706a2c72e29d1f32785ce/pystac/extensions/base.py#L208
- `TemporalExtent` constructor edge cases, including invalid interval arguments https://github.com/azavea/pystac/blob/2605f271da7e9e267cf706a2c72e29d1f32785ce/pystac/collection.py#L359
- Making an href relative when `start_is_dir=True` https://github.com/azavea/pystac/blob/2605f271da7e9e267cf706a2c72e29d1f32785ce/pystac/utils.py#L42
- `geometry_to_bbox` https://github.com/azavea/pystac/blob/2605f271da7e9e267cf706a2c72e29d1f32785ce/pystac/utils.py#L161
- Methods within `ResolvedObjectCollectionCache` https://github.com/azavea/pystac/blob/2605f271da7e9e267cf706a2c72e29d1f32785ce/pystac/cache.py#L193
- Tests in EO extension apply method https://github.com/azavea/pystac/blob/develop/pystac/extensions/eo.py
- For several extensions, construct extension object from an item that does not already have extension listed in its `stac_extensions` property (https://github.com/azavea/pystac/blob/2605f271da7e9e267cf706a2c72e29d1f32785ce/pystac/extensions/view.py#L23)
- Edge cases for `StacVersionRange` comparisons https://github.com/azavea/pystac/blob/5a2f9278e76cbfc03643ebd0ee90bc98ab03aaeb/tests/serialization/test_identify.py#L55
- Setting non-null collections on `SingleFileSTACCAtalogExt` https://github.com/azavea/pystac/blob/5a2f9278e76cbfc03643ebd0ee90bc98ab03aaeb/pystac/extensions/single_file_stac.py#L125

**Comment by whatnick** [comment]
This issue should be updated to reference new home, possibly broken up into sub-issues for each section that requires unit tests.

**Comment by lossyrob** [comment]
Closing as this list is out of date.
