### ISSUE TITLE
Collection "inheritance" (data duplication)

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/pystac#177]
Is it possible with PySTAC to cater for the use case described here?
https://github.com/radiantearth/stac-spec/issues/741#issuecomment-678608830
The way this could work is described here:
https://github.com/radiantearth/stac-spec/issues/741#issuecomment-678630740

What I would imagine is that you can specify some kind of parent collection for child collections that you replicate from. So you get a multi-level collection hierarchy. In PySTAC you'd only need to specify metadata per collection and the library would then make the data duplication for the user...

**Comment by gadomski** [comment]
@m-mohr something like this?

```python
class Collection:
    def create_child_collection(self, id: str) -> Collection:
        collection = self.clone()
        collection.id = id
        for item in self.items():
            collection.add_item(item)  # this sets the item's parent
        collection.set_parent(self)
        return collection
```

There's some edge cases to check w.r.t. linking, but is this the general idea?

**Comment by m-mohr** [comment]
Thanks, nice snippet. I hardly remember all the details after two years, sorry. One thing that's to be decided by the user is which collection the item should point back to...

**Comment by gadomski** [comment]
Something like this?

```python
def create_child_collection(self, id: str, move_items_to_child: bool = True) -> Collection:
```

These comments should be enough info for someone to pick this up and make a PR if they want, thanks Matthias.

**Comment by m-mohr** [comment]
No, I meant the actual `collection` field in the Item. It's not quite clear which collection to use there and I think that would be up to the user to decide.

Indeed, I think the code above is enough for now, let's wait for further user demand.
