### ISSUE TITLE
Generate collection summaries field automatically from items

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#178]
Generate a collection's `summaries` property based on the items it contains. See [the summaries detail section of the collection spec](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#collection-fields).

Feature request by @m-mohr

**Comment by lossyrob** [comment]
@m-mohr Would this take as input the field names of the item's `properties` that you want to generate summaries for? What other inputs would be required?

**Comment by m-mohr** [comment]
Having that would be my favorite feature in PySTAC! 🤩

I think by default it would just summarize all properties found, maybe except some fields that usually don't make sense (complex objects/too many array elements) or are available top-level like datetime (already available in in the extent, but the extents could also get populated automatically), license, title, description, ...

A good idea in addition is to let the user choose, indeed. We can also discuss this further in the future.

**Comment by cholmes** [comment]
I was thinking about this more as I wrote up https://github.com/radiantearth/stac-spec/pull/985

I do think there should be a default to summarize all properties 'that make sense'. And then some mechanism to let a user choose. 

For the first I think that's:

* Any property that is a number or a date/time - it's just a min and max range, so easy to do.
* Any string that has less than X number of occurrences. I'd default to like 10-ish, but then give users an option to use a different value here, so they could choose to summarize all fields that have less than 40 if they want, or less than 5. 

Should be sure to capture simple arrays as well. And then like @m-mohr says, ignore datetime, license, provider, title, description, etc. 

For letting a user choose, you probably need to give them options to list the fields to either deny or allow. 

Note that @volaya may have some Planet cycles to look into this, so @lossyrob and @m-mohr - do sound in soon if you have ideas.

**Comment by m-mohr** [comment]
That all makes a lot of sense.

I'm currently implementing stac-fields: https://github.com/stac-utils/stac-fields
I think we could use the fields.json in the package to figure out details about the summaries, e.g. whether the arrays should be merged (e.g. eo:bands) or not (e.g. cube:dimensions). I could also indicate there which fields should not be summarized and other information that may be required to generate meaningful summaries. Then you have a machine-readable source of truth for summaries across all libraries.

**Comment by cholmes** [comment]
> That all makes a lot of sense. A default limit of 10 might be a bit too low and it can also apply to objects, not just strings. For example, a limit of 10 would not summarize the bands for Sentinel-2, which has 10+ bands. I'd rather go for 20 or 25 or so.

Done - that was suggested mostly for the idea, I had no idea of a good number. 

> I think we could use the fields.json from that package to figure out details about the summaries, e.g. whether the arrays should be merged (e.g. eo:bands) or not (e.g. cube:dimensions).

Awesome, that makes a lot of sense to me. Use fields.json as the default, and then the next step could be that a user can set their own JSON in the same form as fields.json that specifies 'their' rules.

**Comment by cholmes** [comment]
There's progress on this in #264 - I've been meaning to sound in with how to approach it but have been slammed.

**Comment by lossyrob** [comment]
Marking this as PySTAC 1.0, though I'm not sure this functionality will make it into the next release - as mentioned there's progress on #264 as a WIP PR. I'm not sure adding the fields.json directly to PySTAC is the right move, or it should pull from some remote place where multiple projects can read from it and make fixes for all users. If the latter, should it be versioned? These are the types of questions we should consider for the next release, and determine if we want to push this feature into PySTAC 1.0 or if it's complex/unresolved enough to kick to the next release.

**Comment by m-mohr** [comment]
> I'm not sure adding the fields.json directly to PySTAC is the right move, or it should pull from some remote place where multiple projects can read from it and make fixes for all users. If the latter, should it be versioned?

 @lossyrob This is already the case. stac-fields is available on GitHub (everyone can contribute) and regularly released on npm, so you can request it from JS Delivr for example:
https://cdn.jsdelivr.net/npm/@radiantearth/stac-fields@1.0.0-beta.6/fields-normalized.json

Once we have a stable release (i.e. after STAC 1.0.0 release), you can also always load the latest 1.x release for example:
https://cdn.jsdelivr.net/npm/@radiantearth/stac-fields@1/fields-normalized.json

**Comment by duckontheweb** [comment]
Closing via #264 as that PR seems to address all of the needs raised here. If anyone disagrees, feel free to re-open.
