### ISSUE TITLE
My COG's coordinates are way off.

### ISSUE THREAD

**Issue by OhioAdam** [stac-utils/pystac#184]
In the [how-to-create-stac-catalogs](https://github.com/stac-utils/pystac/blob/ce3e80a669c42640ed7a50758b2abcf5b96ae5d6/docs/tutorials/how-to-create-stac-catalogs.ipynb) tutorial, I am using my own AWS hosted COG, and the coordinates show up like so: `[-8841012.439576626, 4450469.534876103, -8838872.20278464, 4452609.771668088]`
It shows up normally in the [cogeo map](https://www.cogeo.org/map/) though. Am I doing something wrong?

**Comment by lossyrob** [comment]
This was discussed in the Gitter - it was discovered that the COG was in EPSG:9003 so the coordinates needed to be reprojected to produce a valid bbox and GeoJSON for the Item.
