### ISSUE TITLE
Best practices for dynamically updating catalogs

### ISSUE THREAD

**Issue by rabernat** [stac-utils/pystac#185]
Thanks to all the STAC developers for these great tools. In the Pangeo project, we are working on transferring migrating existing [catalog](https://catalog.pangeo.io/) to STAC. Since we are a python shop, pystac will likely play a big role in this.

I have a somewhat general question about how we should be using STAC. Apologies if this is the wrong place for it...

**What are the best practices for maintaining a large dynamic STAC catalog?**

We will need to be constantly adding to / modifying our catalog entries. Sometimes this will happen in an automated way, sometimes manually. We might also need some sort of GUI for data managers to edit catalogs. I'm having a hard time wrapping my head around how to architecture this.

I see basically two possibilities:
- _The "master" source of truth about the catalog is a series of text-based STAC files._ We create various wrapper layers around this, such as an API service that allows us to update the catalog when a new dataset is added to cloud storage. In this case, pystac would figure heavily.
- _The "master" source of truth about the catalog a database._ We use STAC API to provide a STAC-like interface for browsing / querying the database. We build other utilities for data managers to talk to the database directly.

I'm really curious to hear about best practices. What does a "full stack" cloud-native data management solution with STAC look like.

cc @charlesbluca

**Comment by matthewhanson** [comment]
@rabernat 
I'm not sure this fits your needs, but you might want to take a look at Cirrus: https://github.com/cirrus-geo/cirrus

Which uses your first option where the canonical version of the metadata are STAC files on s3....but everything running through Cirrus gets published to an SNS topic which can be used to keep a dynamic API in sync (this is what I do using [stac-server](https://github.com/stac-utils/stac-server) for [Earth-search](https://earth-search.aws.element84.com/v0)).

Cirrus uses PySTAC for some things, and I'm currently working on incorporating it more and figuring out how to have the Cirrus s3 files be maintained as a fully linked static STAC catalog.

It wouldn't fit all you needs here, such as GUI editing, but sounds like it might be part of the solution. but happy to talk about it more.
