### ISSUE TITLE
Error(s) while Reading Catalogs/Items on a Windows machine

### ISSUE THREAD

**Issue by ppoply** [stac-utils/pystac#187]
Hi,

I'm facing a few errors when trying to read Catalogs or Items on a windows machine.

I'm trying to read both locally existing and HTTPS catalogs. PySTAC is unable to read the catalogs correctly on a Windows machine. Everything works perfectly on my Mac though.

I've put up [this temporary GitHub repo](https://github.com/ppoply-tester/pystac_windows_error) on my buffer account to showcase the issues I've faced. It looks like an issue related to the handling of paths passed into the PySTAC [`from_file()`](https://pystac.readthedocs.io/en/latest/api.html#pystac.STACObject.from_file) method. Specifically related to the [`make_absolute_href()`](https://github.com/stac-utils/pystac/blob/0b42dbe588ca6dead93e67e5927ecc4ef7fd462c/pystac/utils.py#L78) method in the utils.py file. I did some debugging by printing what the [`make_absolute_href()`](https://github.com/stac-utils/pystac/blob/0b42dbe588ca6dead93e67e5927ecc4ef7fd462c/pystac/utils.py#L78) method is returning in its every call. [This](https://github.com/ppoply-tester/pystac_windows_error/blob/0d2d495f27fdc160ba9122daa13b4cbcf1a0b1ba/utils.py#L78) is my variant of the method (contains extra lines for printing the returned string).

In [error1 notebook](https://github.com/ppoply-tester/pystac_windows_error/blob/master/error1.ipynb), I'm trying to read the Landsat catalog from HTTPS and then also trying to navigate to the first catalog that contains an item (similar to what has been done in the [quickstart notebook](https://github.com/stac-utils/pystac/blob/develop/docs/quickstart.ipynb) of PySTAC). 

As you may see, The error encountered is as follows : 

`ConnectionError: HTTPSConnectionPool(host='landsat-stac.s3.amazonaws.comc', port=443): Max retries exceeded with url: /catalog.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000198F3A7ACC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))`
 
While reading the Landsat catalog, the call to the [`make_absolute_href()`](https://github.com/ppoply-tester/pystac_windows_error/blob/0d2d495f27fdc160ba9122daa13b4cbcf1a0b1ba/utils.py#L78) method returns this:

https://landsat-stac.s3.amazonaws.comC:/catalog.json

instead of this : 

https://landsat-stac.s3.amazonaws.com/catalog.json

You can see the **`C:`** in between which is causing the issue. The ConnectionError is attributed to this only. 

In [error2 notebook](https://github.com/ppoply-tester/pystac_windows_error/blob/master/error2.ipynb), I'm trying to read an item through its Absolute link and encountering the same error.

However, In [error3 notebook](https://github.com/ppoply-tester/pystac_windows_error/blob/master/error3.ipynb), I'm trying to read a locally existing catalog (same as the one mentioned In the PySTAC tutorials - [example-catalog](https://github.com/stac-utils/pystac/tree/develop/docs/tutorials/example-catalog)) and facing this error : 

`URLError: <urlopen error unknown url type: c>`

The problem still seems related to the correct resolution of Windows-style local paths.

The error caused in the [error1](https://github.com/ppoply-tester/pystac_windows_error/blob/master/error1.ipynb) and [2](https://github.com/ppoply-tester/pystac_windows_error/blob/master/error2.ipynb) notebooks is mostly due to use of [abspath()](https://docs.python.org/3/library/os.path.html#os.path.abspath) method on [this line](https://github.com/stac-utils/pystac/blob/0b42dbe588ca6dead93e67e5927ecc4ef7fd462c/pystac/utils.py#L110) of the [`make_absolute_href()`](https://github.com/stac-utils/pystac/blob/0b42dbe588ca6dead93e67e5927ecc4ef7fd462c/pystac/utils.py#L78) method in the utils.py file. Replacing it with this makes the error go away : 

`abs_path = _pathlib.join(start_dir, parsed_source.path)`

Even after making this change, The error faced in the [error3 notebook](https://github.com/ppoply-tester/pystac_windows_error/blob/master/error3.ipynb)(locally existing STAC access) still persists. One way to get past it is by converting the local file path into a correctly resolved windows compatible URI with the help of the [pathlib](https://docs.python.org/3/library/pathlib.html) library and passing it to the  [`from_file()`](https://pystac.readthedocs.io/en/latest/api.html#pystac.STACObject.from_file) method :

`uri = pathlib.Path(catalog_path).resolve().as_uri()`

I'm not sure that these are the optimal ways of getting rid of the errors. Everything works fine on a Mac, and the errors are specific to Windows only.

Please Kindly look into this. Thank You.

**Comment by lossyrob** [comment]
Hi @ppoply, thanks for the detailed writeup and examples. This should be straightforward to fix as it seems `make_absolute_path` is just doing the wrong thing with windows paths with drive prefixes. Good suggestion on pathlib, though I'm hesitant to add the `pathlib` library as I think it's valuable to keep PySTAC having as few dependencies as possible.

The hardest part of this issue will be to capture the error in unit tests that can be integrated into our CI - we currently don't test against windows environments. It's probably worth looking into how to run the unit tests inside a windows environment through GitHub Actions, but that could be solved in a follow up issue.

Fixing this would be a good contribution from a PySTAC user who uses Windows; the approach I would take would be:
- encapsulate the failures shown in the example notebooks here into unit tests that fail in a windows environment
- modify `make_absolute_href` and any other related logic to make those tests pass
- make a PR with the changes and the tests

If you or anyone else is interested in taking this one on comment here!

**Comment by CloudNiner** [comment]
> I'm hesitant to add the pathlib library as I think it's valuable to keep PySTAC having as few dependencies as possible

I understand this concern, but I'm curious as to how it applies here. Pathlib is part of the Python std lib for Python 3.4+ and pystac [declares support for 3.6+](https://github.com/stac-utils/pystac/blob/develop/setup.py#L49-L51). As far as I understand it, pathlib seems to be the way to handle these types of issues these days.

**Comment by lossyrob** [comment]
🤦 when I hovered over the pathlib link I thought that was linked to `pypi` - you're right, scratch that, we should be using `pathlib`!

**Comment by ppoply** [comment]
Hi @lossyrob, 

Thanks for the comprehensive feedback. I'm definitely willing to help with this one. I'll try to follow the approach you mentioned and make a PR. Do comment here in case you would have anything else to add to the suggestions you have already provided. 

Using `pathlib` or not would surely be your decision. I'm willing to help with that too if needed (with regard to testing on Windows Environments).  Do comment your thoughts about this.

**Comment by lossyrob** [comment]
@ppoply - It slipped my mind that I actually have a workaround for testing windows path issues. See [an example here](https://github.com/stac-utils/pystac/blob/develop/tests/test_utils.py#L115), by allowing patching of the path package used [as seen here](https://github.com/stac-utils/pystac/blob/develop/pystac/utils.py#L9). If we move to utilizing `pathlib` (which again seems like a good move, or at least very much an option) that workaround might need updating.

Another option we could explore is modifying the GitHub Actions [CI workflow](https://github.com/stac-utils/pystac/blob/develop/.github/workflows/continuous-integration.yml#L13) to also run tests in a windows environment(https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources), so that the CI would tell us if something didn't work with windows paths. This might effect the current unit tests as it may make assumes around unix-like paths explicitly except for the one windows path test I linked above.

**Comment by ppoply** [comment]
Seems to be fixed. Thank you!
