### ISSUE TITLE
Support the scientific extension

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#194]
In follow up to #193, I'm doing to work on supporting the Scientific Extension.

https://github.com/radiantearth/stac-spec/tree/dev/extensions/scientific

**Comment by duckontheweb** [comment]
Hi @schwehr , just curious if there is a timeline for getting this into a new release? We're working with collections that implement this extension and it would be helpful to be able to access the properties using `collection.ext['scientific']` rather than getting them via the dictionary.

**Comment by lossyrob** [comment]
@duckontheweb this issue was closed by #199, and released as part of pystac 0.5.4. Let us know how the extension works for you and submit issues for any problems you hit!

**Comment by schwehr** [comment]
Thanks @lossyrob for closing this.  Sorry I didn't.

**Comment by duckontheweb** [comment]
> @duckontheweb this issue was closed by #199, and released as part of pystac 0.5.4. Let us know how the extension works for you and submit issues for any problems you hit!

Awesome, thanks! I'll upgrade (I was on `0.5.3`).
