### ISSUE TITLE
DOI support

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#202]
An issue to think through possibilities. In working on the scientific extension, I made a little class to represent DOIs.  I want to be able to easily ignore things like dx.doi.org versus doi.org and http versus https.   That caused me to look more into the world of DOIs.  There is an API to get info on an doi.  If we made it easy to get all that info from the doi lookup, what would users do with it?  Can we make it easier for users to get bibtex and other citation formats?  What if we make it easy to cache the api results?

**Comment by gadomski** [comment]
This feels out-of-scope for PySTAC ... downstream projects can combine the [doi attribute](https://pystac.readthedocs.io/en/stable/api/extensions/scientific.html#pystac.extensions.scientific.Publication.doi) with any third-party libraries they'd like to do lookups. Closing as wontfix, please re-open if you think this should be in scope for the library.
