### ISSUE TITLE
Don't use _pathlib in utils.py

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#215]
Don't do this in `utils.py`:

```python

import os

# [SNIP]

# (i.e. testing Windows path manipulation on non-Windows systems)
_pathlib = os.path
```

instead do: 

```python
import os
```

And in testing, use `@mock.patch('os.patch')`...

```python
import mock

# [SNIP]
    @mock.patch('os.path')
    def test_make_relative_href_windows(self, mock_path):
        # TODO: set behavior of mock_path.
```

**Comment by jsignell** [comment]
Just a note that when I started working on #619 in #1002 I removed `_pathlib`. I'm not sure we even really need to patch the os patch since we can just rely on CI to run the tests on the correct architecture.
