### ISSUE TITLE
Flush out the remainder of test_link.py

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#218]
Things todo and questions to answer from working on #211 

- ~Does `class Link` need an \_\_eq\_\_?  And the same for many of the other classes.  The default behavior isn't very useful~ - Moved to #222 
- test_minimal: Cannot call link.get_href() after set_owner.  Got an error
- test_minimal: Test link.resolve_stac_object()
- Test get_href when href is absolute and there is an owner
- Test get_absolute_href when there is an owner
- Test when resolve_stac_object on link when target is a str.

**Comment by duckontheweb** [comment]
Moving this out of the 1.4.0 release since it does not seem critical

**Comment by jsignell** [comment]
It is a little hard to map these back to the current state of the tests, but I am fairly confident that all the cases listed in the original description are captured in the tests at this point.

This is probably fine to close.

**Comment by gadomski** [comment]
Yeah, I think so too. There are some slightly worrying misses in the [`link.py` coverage](https://app.codecov.io/gh/stac-utils/pystac/blob/main/pystac/link.py) but I don't think any of the suggested fixes in this issue touch those. Closing as done.
