### ISSUE TITLE
Improve test coverage of pointcloud extension

### ISSUE THREAD

**Issue by whatnick** [stac-utils/pystac#248]
The pointcloud extension sticks out in codecov as one of the areas with 81% unit-test coverage. More tests will improve validation of the code-base and help capture edge cases : https://codecov.io/gh/stac-utils/pystac/src/0630c4f4f495763435730e770e533099e9d9d839/pystac/extensions/pointcloud.py

**Comment by gadomski** [comment]
I can take this one on.
