### ISSUE TITLE
Sat extension cannot be enabled on an item

### ISSUE THREAD

**Issue by alkamin** [stac-utils/pystac#257]
When attempting to add the `sat` extension to an item, `item.ext.enable('sat')`, an exception is raised:

`pystac.extensions.ExtensionError: 'sat' is not an extension registered with PySTAC`

I also attempted to use the enum directly, `item.ext.enable(pystac.extensions.Extensions.SAT)`, and that failed in the same way. Other extensions were able to be enabled without issue.

**Comment by lossyrob** [comment]
Closing this issue as there's tests that perform this action and after investigation no bug was found; perhaps a versioning issue. Please re-open if necessary.
