### ISSUE TITLE
Ensure migration happens correctly with SAR extension

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#262]
@m-mohr's mentioned in Gitter:

> There are a couple of things missing in SAR, I think. It had some old array-typed fields which are now separate numerical fields, see https://github.com/Open-EO/openeo-js-commons/blob/master/src/migrate/collections.js#L215

**UPDATE (@duckontheweb):** Will not add a migration for this since it only applies to pre-0.8 catalogs, which we do not support.

**Comment by m-mohr** [comment]
@lossyrob I've found some other properties that don't seem to be migrated (or I've missed them):

- with 0.9.0 eo:epsg changed to proj:epsg
- with 0.8.0 pc:schema to pc:schemas
- with 0.9.0 sar:type to sar:product_type and sar:polarization to sar:polarizations
- with 0.7.0 sar:off_nadir to non-existing, but translates to view:off_nadir now
- still need to figure out at which point sar:incidence_angle, sar:relative_orbit, sar:observation_direction have been removed. Translates to view / sat extension fields though.
- 'sar:pass_direction' translates to 'sat:orbit_state', but not 1:1

**Comment by m-mohr** [comment]
> It had some old array-typed fields which are now separate numerical fields

Mapping:
sar:resolution => sar:resolution_range, sar:resolution_azimuth
sar:pixel_spacing => sar:pixel_spacing_range, sar:pixel_spacing_azimuth
sar:looks => sar:looks_range, sar:looks_azimuth, sar:looks_equivalent_number (opt)

**Comment by m-mohr** [comment]
One more thing: Do you migrate the Collection extents that have changed with 0.8? Can't find any code related to it.

**Comment by duckontheweb** [comment]
> @m-mohr's mentioned in Gitter:
> 
> > There are a couple of things missing in SAR, I think. It had some old array-typed fields which are now separate numerical fields, see https://github.com/Open-EO/openeo-js-commons/blob/master/src/migrate/collections.js#L215



It looks like this change happened in v0.7.0, which we no longer support in PySTAC, so I am not going to add a migration for this.

> * with 0.7.0 sar:off_nadir to non-existing, but translates to view:off_nadir now

Same for this one.

> * 'sar:pass_direction' translates to 'sat:orbit_state', but not 1:1

I couldn't find a reference to this change in the STAC spec CHANGELOG. @m-mohr @lossyrob Do you know when this changed?

**Comment by duckontheweb** [comment]
> * still need to figure out at which point sar:incidence_angle and sar:relative_orbit have been removed. Translates to view / sat extension fields though.

I wasn't able to find any references to these fields in the STAC spec CHANGELOG or in the history of the SAR Extension README in the `stac-spec` repo. If we think this change happened pre-0.8 I'll leave this out as well.

**Comment by duckontheweb** [comment]
> * with 0.8.0 pc:schema to pc:schemas

Since we don't support pre-0.8 catalogs anymore, this also shouldn't be necessary.

**Comment by duckontheweb** [comment]
I'm going to close this since I believe we have addressed all of the migrations that apply to STAC >=0.8. If it turns out that the `sar:incidence_angle`, `sar:relative_orbit`, or `sar:pass_direction` migrations apply to STAC >= 0.8 we should open separate issues for those.
