### ISSUE TITLE
Large catalog async optimizations

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac#274]
I've been playing with using asyncio/httpx/aiofiles/aioboto3 to improve the speed of reading and writing of large catalogs (10+ million). Right now I'm just wrapping around PySTAC but think some of this could be incorporated into it. 

Opening up this ticket to see if anyone else has been working with async functions here.

**Comment by TomAugspurger** [comment]
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md has some information on how Azure designed their libraries for working with multiple HTTP networking libraries (including sync and async). https://devblogs.microsoft.com/azure-sdk/custom-transport-in-python-sdk-an-httpx-experiment/ is an example plugging in httpx through that mechanism.

**Comment by gadomski** [comment]
Closing after some discussion at today's [**stac-utils** working group meeting](https://docs.google.com/document/d/1_Vd290Qiz6I7LFJD23KE31xjfNVeIRjtlSKmBRoZ8ME). It seems as though writing your own IO functions that produce PySTAC data structures is the way to go: One example of this pattern is [this method in **stac-asset**](https://github.com/gadomski/stac-asset/blob/0901d6b200d20bf75beb77b5c86d2c20b219bfab/src/stac_asset/client.py#L200-L202).
