### ISSUE TITLE
Implement Extension: Checksum

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#29]
Implement the Checksum extension for adding checksum data to Links and Assets.

https://github.com/radiantearth/stac-spec/tree/v0.8.0/extensions/checksum

**Comment by lossyrob** [comment]
This might require some new architecture that allows for Assets and Links to be parsed into extended objects - currently we only do this for STACObject types.

**Comment by schwehr** [comment]
Should this extension just manage the tags? Or should it actually understand the contents of the hash?  If it does understand them, should it have its own implementation of handling the payload? If so, should it use a new embedded handler or should it use an existing multihash library from pypi?

**Comment by lossyrob** [comment]
Checksum got merged into file extension, which was implemented
