### ISSUE TITLE
Test catalogs should not have a collection as a root catalog

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac#292]
The [planet-example-1.0.0-beta.2](https://github.com/stac-utils/pystac/tree/develop/tests/data-files/catalogs/planet-example-1.0.0-beta.2) test catalog has a Collection as the root catalog. 

Now that Collection does not inherit from Catalog (i.e., a Collection is not a Catalog) it cannot be the root catalog.

This example should be nested under a root catalog and tests updated accordingly.

**Comment by lossyrob** [comment]
Based on https://github.com/radiantearth/stac-spec/pull/1091, this should be closed, yeah?
