### ISSUE TITLE
Adding assets to a collection

### ISSUE THREAD

**Issue by fabricebrito** [stac-utils/pystac#293]
The [collection spec](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md) foresees the possibility to add assets to a STAC collection.

This issue reports the lack of methods to add assets to a STAC collection

**Comment by lossyrob** [comment]
Thanks for reporting - this is work that needs to be done for the 1.0.0-RC1 upgrade, which is slated to happen over the next couple of months.

For now, if you need assets on collections you can take advantage of the [Collection.extra_fields](https://github.com/stac-utils/pystac/blob/main/pystac/collection.py#L38) property on collection, which holds any fields that PySTAC doesn't parse into STAC metadata at the top level of the collection. If you add an "assets"  key to that dict, it will be written out when you save the Collection.
