### ISSUE TITLE
Removing items from a catalog will leave files

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac#301]
If a catalog has Items added to it, is then saved and generate_subcatalogs is run, then saved again, the original files will still exist on disk.

I'm not sure if PySTAC should be responsible for removing these files or not, but it's at least something users should be made aware of.

One possibility is to add in delete_stac_object to STAC_IO, but then also add in a cleanup keyword to PySTAC to enable..I'm uncomfortable with PySTAC transparently deleting files.

**Comment by gadomski** [comment]
I don't think PySTAC should be responsible for synchronizing files on disk and the in-memory STAC catalog -- to me, this feels very hard and out of scope. I view the act of saving a STAC catalog to disk as "snapshotting" the catalog, and it's the user's fault if they snapshot a mutated catalog on top of its original snapshot. The user (IMO) should take responsibility for deleting things:

```python
catalog.save("a/location")
catalog = change_things(catalog)
shutil.rmtree("a/location")
catalog.save("a/location")
```

One way to inform the user that they're overwriting data is to log a warning every time a file is being overwritten during a save operation. @matthewhanson would that be good enough?
