### ISSUE TITLE
Collection properties

### ISSUE THREAD

**Issue by aliasmrchips** [stac-utils/pystac#311]
The `Collection` class includes a `properties` field which does not appear to be part of the [specification](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md)

I would prefer adding it to the specification, but more likely to remove it here.

**Comment by lossyrob** [comment]
Thanks for reporting - this will be part of the upgrade to the latest version of the spec, and properties will be dropped on Collections in the next release. #309 contains this change, will close this issue when that gets merged.

**Comment by aliasmrchips** [comment]
Thanks. Will that also help with extension support in stac-fastapi (e.g., https://github.com/stac-utils/stac-fastapi/issues/121)? Or am I jumping too far ahead?

**Comment by lossyrob** [comment]
stac-fastapi uses [stac-pydantic](https://github.com/stac-utils/stac-pydantic), not PySTAC, so work here won't affect stac-fastapi. I've experienced something similar with that issue, and will comment there.
