### ISSUE TITLE
Copyright date, owner

### ISSUE THREAD

**Issue by l0b0** [stac-utils/pystac#312]
The license file says the code is "Copyright 2020 Azavea [http://www.azavea.com]". The date should probably be updated, but more importantly, does this mean all copyright is assigned to Azavea when contributing?

**Comment by lossyrob** [comment]
> does this mean all copyright is assigned to Azavea when contributing

No, it doesn't. There was never a CLA put into place that would have legally transferred copyright ownership over to another entity (as is done for instance in Apache projects), so all original authors of code maintain copyright over their contributions. This library was primarily developed by myself and colleagues when I was under employment from Azavea, and therefore a lot of the code is in fact copyright Azavea, but my own contributions in the past several months as well as the many other non-Azavean contributors have a copyright assignment to whatever individual or organizations had contributed to the codebase.

The copyright could be updated to include all individuals and organizations who contributed code - but that's a lot of work to create and maintain, and we're not following the type of IP rigor that would require that level of detail (e.g. an IP review from something like the Eclipse Foundation, which I've been through with GeoTrellis...) Instead we should remove the copyright notice to avoid confusion, and the update the date - should be a simple PR if you'd be willing to update, or else I'll get around to it and close this issue when it's done. Thanks!

Note: I'm not a lawyer, but have been through a lot of related IP stuff and am pretty sure I'm speaking correctly to the letter of some law or another.
