### ISSUE TITLE
Need to implement eo extension for collections

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#319]
https://github.com/stac-extensions/eo

Electro-Optical Extension Specification says:
- Title: Electro-Optical
- Identifier: https://stac-extensions.github.io/eo/v1.0.0/schema.json
- Field Name Prefix: eo
- Scope: Item, Collection

pystac only implements `EOItemExt`

**Comment by lossyrob** [comment]
I believe that's a bug in the spec. What does Collection implement? There is no mention of collections elsewhere; I think this may be a holdover from when Collections had properties that could hold common item properties, and eo information was often held there.

**Comment by schwehr** [comment]
Earth Engine currently only has stac collections and we need the band info in collections

**Comment by lossyrob** [comment]
I think what you're looking for is summaries and/or item_assets.

Summaries for the eo extension are implement on the branch [here](https://github.com/stac-utils/pystac/blob/feature/rde/1.0-refactors/pystac/extensions/eo.py#L354). item_assets are implemented [here](https://github.com/stac-utils/pystac/blob/feature/rde/1.0-refactors/pystac/extensions/item_assets.py). This makes me think we may want to include AssetDefinitions as objects that can be wrapped in an extension so that the extension objects can be used to retrieve extension properties from asset definitions.

**Comment by lossyrob** [comment]
Based on https://github.com/radiantearth/stac-spec/pull/1078 I think my understanding may be outdated (by 18 days). Asking some clarifying questions on Gitter about how collection (and now catalog) summaries are handled with stac_extensions, and how item_assets may play into this as well. If a Collection/Catalog is supposed to extend for example eo if summary information contains eo fields, then I agree we need a way to enable it on Collections/Catalogs

**Comment by lossyrob** [comment]
As described in https://github.com/radiantearth/stac-spec/issues/1120, both Collection and Catalogs need implementation for most extensions as the summary information can contain extension information. This issue is resolved when extensions are implemented for each of the object types that they apply. Related to #327

**Comment by lossyrob** [comment]
Note that Catalogs are now dropping summaries (https://github.com/radiantearth/stac-spec/pull/1122), so this only needs to account for Collection extensions

**Comment by duckontheweb** [comment]
@schwehr If you're game, this is something we would love to get into the 1.0 release. Any chance you'd have some availability to work on it in the next few weeks?

**Comment by schwehr** [comment]
I can try to give it a go next week.  It would be nice to have.

**Comment by schwehr** [comment]
Starting to look at doing the Collection part.  I'm totally not familiar with mixin stuff, but the `pystac.Item` Mixin seems wrong.  I need to dig deeper into it to understand now `ExtensionManagementMixin` works

```
class EOExtension(
    Generic[T], PropertiesExtension, ExtensionManagementMixin[pystac.Item]
):
```

When the concrete classes have `pystac.Item`:

```
class ItemEOExtension(EOExtension[pystac.Item]):
class AssetEOExtension(EOExtension[pystac.Asset]):
class SummariesEOExtension(SummariesExtension):
```

**Comment by schwehr** [comment]
Ok... looking at datacube.py, I am starting to get it.

```python
class EOExtension(
    Generic[T],
    PropertiesExtension,
    ExtensionManagementMixin[Union[pystac.Collection, pystac.Item]]
):
```

**Comment by duckontheweb** [comment]
@schwehr I'm aiming to get an RC1 release out in the next couple of days and would love to include this. Does that seem feasible?

**Comment by schwehr** [comment]
> @schwehr I'm aiming to get an RC1 release out in the next couple of days and would love to include this. Does that seem feasible?

I gave it an initial look and ended up with more questions than answers.  Am about to be OOO on leave for a week or two

**Comment by duckontheweb** [comment]
Okay, no worries. I'll take a crack at it and see how far I get.

**Comment by duckontheweb** [comment]
Moving this out of the RC1 release since it will represent a feature add rather than a breaking change.

**Comment by duckontheweb** [comment]
@lossyrob @schwehr I'm looking at this in more detail right now and I think I'm still confused about what exactly needs to be implemented. We have already implemented this extension for both Items and Assets, and we already have Collection-level summaries implemented. Is anything further needed?

**Comment by schwehr** [comment]
I'm confused too.  I think we need someone to create a Collection example here: https://github.com/stac-extensions/eo/issues

**Comment by duckontheweb** [comment]
I'm confident that no change is needed for this issue. My understanding is that the scope of the Electro-Optical Extension includes Collection only because extension properties can be summarized at the Collection level. We have implemented this in PySTAC, so no further changes should be necessary.
