### ISSUE TITLE
Update extension pydoc strings to match new extension architecture

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#326]
Extensions were refactored as part of #309; however, ensuring docstrings were up to date and matching the new architecture was left as a TODO.

This issue covers each extension besides item-assets and datacube, which were implemented as part of that PR and are tracked in #325 and #324 .

One approach to this work is to take on individual extensions, and work through the docstrings and test to make sure they are completely up to date, as well as check the sphinx docs to make sure they are correct.

This should take into the account the work to remove type info from docstrings encapsulated in #323 

Extensions covered by this issue:
- [x] eo (#355)
- [x] file (#442)
- [x] label (#442)
- [x] pointcloud (#558)
- [x] projection (#372)
- [x] sar (#556)
- [x] sat (#509)
- [x] scientific (#372)
- [x] timestamps (#513)
- [x] version (#442)
- [x] view (#372)

**Comment by lossyrob** [comment]
Also we may want to consider doing the work for #327 as part of focusing on each extension.

**Comment by duckontheweb** [comment]
Closed by all PRs listed in description.
