### ISSUE TITLE
Implement collection summary functionality

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#327]
In #309, the ability to extract collection summary information for extensions was implemented for the eo extension (see `SummariesEOExtension` in `extensions/eo.py`). This should be implemented for each other extension, and tested across all the extensions, as well as pydocs written for that functionality.

Top level sphinx documentation should also be written for the summaries extensions as a pattern.

Summary information should only be used where it makes sense; e.g. if something will be a large range of discrete values that doesn't makes sense to put into a range, then we shouldn't make a summary entry for it.

Thought should be put into how the CommonMetadata works here - should we have a similar extension functionality for getting and setting common metadata summary information?

Extensions this issue potentially applies to:
- [x] datacube (no summary fields according to [stac-utils/stac-fields](https://github.com/stac-utils/stac-fields))
- [x] eo (testing) (#355)
- [x] file (Removed in #442, no summary fields according to [stac-utils/stac-fields](https://github.com/stac-utils/stac-fields))
- [x] item_assets (Collection summaries do not apply to this extension)
- [x] label (#484)
- [x] pointcloud (#558)
- [x] projection (#372)
- [x] sar (#556)
- [x] sat (#509)
- [x] scientific (#372)
- [x] timestamps (#513)
- [x] version (no summary fields according to [stac-utils/stac-fields](https://github.com/stac-utils/stac-fields))
- [x] view (#372)

**Comment by duckontheweb** [comment]
@m-mohr My understanding is that Collection summaries do not apply to the Item Assets Extension since it only has Collection scope. Is that correct?

**Comment by m-mohr** [comment]
Yes, indeed. (Sorry for the misclick.)

**Comment by duckontheweb** [comment]
@lossyrob I think I'm going to go ahead and start the release without the Datacube Extension summaries. I can add those in a patch release early next week.
