### ISSUE TITLE
RFC: pre-commit hooks for QA tasks

### ISSUE THREAD

**Issue by l0b0** [stac-utils/pystac#366]
Would you be interested in some simple configuration to automatically run flake8, yapf, mypy etc. when committing files? I've already set up [pre-commit](https://pre-commit.com/) in another few projects, and it's super helpful:

- No need to manually run standard QA commands before checking in.
- Checks only the files you're committing at that point, so it's fast.
- Can tie straight into the binaries installed from requirements-dev.txt.
- Can also be run in the CI pipeline, making for a simpler CI script which just runs `pre-commit run --all-files` to run all the checks.
- Runs all the checks even if some of them fail and *then* reports the exit code, so you'd get more information than the current build script.

**Comment by vincentsarago** [comment]
is this the same issue as https://github.com/stac-utils/pystac/issues/390 @l0b0 ?

**Comment by l0b0** [comment]
Err, yes. :blush: Didn't realise I'd already created this, but somehow the other issue got more attention.

**Comment by duckontheweb** [comment]
Superseded by #390
