### ISSUE TITLE
Raise exception on attempt to extend object not implementing that extension

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac#370]
Calling, for instance, `pystac.extensions.eo.EOExtension.ext` on an `Item` that does not have the EO schema URI in its `stac_extensions` list will succeed and return an `ItemEOExtension` instance. You can then read and write fields like `eo:cloud_cover` even though the `Item` doesn't actually implement that extension.

It seems like the desired behavior here would be to raise an exception when using `ext` on an object that does not implement that extension for 2 reasons:

1. When using PySTAC to read existing STAC Items, this could mask a problem with an invalid object
2. This will interfere with the edge case where a user has custom fields with a prefix that overlaps with one of the extensions (maybe because the custom fields predate the extension). In this case, the fields should not be treated as if they are defined by the extension.

Originally raised as part of [this PR comment](https://github.com/stac-utils/stactools/pull/113#discussion_r638974407) in stac-utils/stactools

**Comment by gadomski** [comment]
I haven't seen many cases where an `Asset` exists before the `Item` does. My instinct is to raise an exception when trying to extend an un-parented `Asset`. If folks really need to work around that exception, they can modify the properties directly.

**Comment by lossyrob** [comment]
My preference would be for an exception not to be thrown if the Asset doesn't have an owner, and perhaps give a warning in the documentation. This way users can build up assets before attaching them to items legitimately if that is better for their workflow. I'd rather be trusted by the library to do the right thing than to be blocked by an exception for a legitimate usage.

**Comment by gadomski** [comment]
@lossyrob how should the attachment work in this case? Would you want the `Item` to "inherit" extensions from the `Asset`? Or is it the dev's responsibility to turn on the extension in the `Item`?

**Comment by lossyrob** [comment]
The latter case - if you use an `*Extension` object to access properties on the Asset that doesn't have an Item, then it's on the user to make sure the Item it is associated with has the proper extensions enabled.

**Comment by duckontheweb** [comment]
The other option I considered was to make the `Asset` class "extension-aware" in some way. Then we could do a check when the asset is added to an Item and add extension URIs as necessary.

I haven't thought through the implementation in detail, but one possibility would be to extract the `stac_extensions` property out of `STACObject` and into a `Extensible` base class that both `STACObject` and `Asset` could inherit from. This might allow us to make the `ExtensionManagementMixin` generic over `Extensible` instead of `STACObject`, and then the `Asset` would be responsible for maintaining its own internal list of extension URIs if it is not owned or updating the owning Items's list if it is owned. Definitely some nuance to work out there, though.

**Comment by duckontheweb** [comment]
I can start by having the call succeed for un-owned and then we can always add a feature/fix to update the owning Item when adding an Asset. The breaking change is really raising the exception, so I wanted to make sure we had that ironed out for 1.0.
