### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by BobinMathew** [stac-utils/pystac#385]
This repo is missing a Code of Conduct.
Cant I give a PR ?

**Comment by duckontheweb** [comment]
Yes, please! That's definitely something that we should have. 

I think it would be good to make it consistent with the [Code of Conduct in the STAC spec repo](https://github.com/radiantearth/stac-spec/blob/master/CODE_OF_CONDUCT.md), but I'm also open to discussion of other ideas.

**Comment by duckontheweb** [comment]
Closed via #399
