### ISSUE TITLE
tests/extensions/test_datacube.py and test_item_assets.py are missing

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#388]
Along with this, what does "Tests creating a custom extension" mean in `test_custom.py`?

**Comment by itcarroll** [comment]
I'm in no way connected to this, but I was just looking at `tests/extensions/test_datacube.py`. I also see `test_item_assets.py`. Perhaps the issue may be closed?

**Comment by gadomski** [comment]
> I'm in no way connected to this, but I was just looking at tests/extensions/test_datacube.py. I also see test_item_assets.py. Perhaps the issue may be closed?

Agreed.

> "Tests creating a custom extension" mean in test_custom.py?

There's not much there in the way of actual tests, but I guess it's a static code example of creating a new extension, that could be used by new extension implementors? I don't see any reason to remove it right now.
