### ISSUE TITLE
RFC: pre-commit support

### ISSUE THREAD

**Issue by l0b0** [stac-utils/pystac#390]
[pre-commit](https://pre-commit.com/) is a great way to make it easier to commit only verified code, and would replace most of the contents of the `scripts` directory with configuration.

With reference to a [template project](https://github.com/linz/template-python-hello-world/):

- [.pre-commit-config.yaml](https://github.com/linz/template-python-hello-world/blob/3abc3c3ab4dd651cd71068f88cf67ba29ce4f81e/.pre-commit-config.yaml) configures each of the hooks. Picking apart the first one:
   - `entry: black` is the executable which is run
   - [`language: system`](https://pre-commit.com/#system) means it expects the executable to be on the `PATH`, for example by activating a virtualenv where Black is installed.
   - `stages: [commit]` means the command can be installed as a pre-commit hook (the default), see below. Another common stage is `commit-msg`, which can be used to verify the commit message.
   - `types: [python]` runs the executable for each *version controlled* file of this type, so there's no need to fiddle with recursive globs and unusual extensions.
- A single command, `pre-commit run --all-files`, runs all checks on all files.
- Another single command, `pre-commit install --hook-type=pre-commit --overwrite` installs Git hooks corresponding to each of the configured `commit` stage entries. This automatically runs all of the checks (even if an early one fails) when committing, printing the output of the command for reference (such as `flake8` errors) and returning a non-zero exit code if any of the tests failed. For code formatters like Black it's also clever enough to detect file changes, and treats those as errors (since they should be staged). It even takes care of stashing changed files which are not staged while running the checks, to avoid committing a broken set of lines.

What do you think? It's certainly made the daily work much easier.

**Comment by gadomski** [comment]
As a development tool, it looks pretty handy. One question, which I wasn't able to answer through a quick docs skim, is "can I selectively disable/enable `pre-commit` during development?" I often use `git commit` like `command-s`, stashing changes into a work-in-progress branch before interactively rebasing them into one or more better-constructed commits later. These intermediate commits might not be "correct" per our project configuration but I don't really care, I'm working on functionality and I'll touch up the paint job later. Is `pre-commit` compatible for my workflow? Obviously doesn't need to be, but others might have similar workflows 🤷🏽.

**Comment by vincentsarago** [comment]
> can I selectively disable/enable pre-commit during development?

I guess you can just do `pre-commit uninstall`

**Comment by gadomski** [comment]
Consider me +0 if that's the case, then. I don't mind it being in the toolchain, but I guess I'm used to "run the appropriate file from the `scripts/` directory before opening a PR". However, not everyone does that, so I could see `pre-commit` being useful. Will they install `pre-commit`, though?

**Comment by vincentsarago** [comment]
We use pre-commit in most of our project, I think it's fine asking dev to install and setup pre-commit if they want to contribute e.g https://github.com/cogeotiff/rio-tiler/blob/master/CONTRIBUTING.md#contributing 

It's also fine if you don't install pre-commit but then it might fail in CI (if the CI runs pre-commit)

**Comment by l0b0** [comment]
> can I selectively disable/enable `pre-commit` during development?

Yes, `git commit --no-verify` will skip the pre-commit and commit-msg hooks, letting you commit partial work. As a contributor you can then just run `pre-commit run --all-files` before creating a PR, to clean up any remaining issues.

**Comment by gadomski** [comment]
In that case move me to 👍🏽, thanks @l0b0.

**Comment by lossyrob** [comment]
I'm not a pre-commit user, and in the past I've found the hooks interfere with my workflow (often I want to make point commits that I then extend later via rebasing, and don't want those commits blocked by pre-commit for e.g. formatting issues). But as mentioned, I can just avoid installing the hooks and use it just like scripts/test was used. I like scripts/test because it follows a consistent [scripts to rule them all](https://github.com/github/scripts-to-rule-them-all) approach that I take across repositories, which makes things really consistent project to project. However, that's just my personal preference and if other contributors think pre-commit is an improvement I'm more than willing to learn a new tool, and I'm +1
