### ISSUE TITLE
Update package metadata in setup.py

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac#403]
* Add [`project_urls`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls) with links to docs, bug tracker, and Gitter channel (should we use `azavea/pystac` for this, or do we want to create a new one?)
* Include LICENSE file in distribution. I think this is technically required by the Apache license and in any case is probably good practice.
* Should `Azavea`/`info@azavea.com` still be the `author`/`author_email`. I want to make sure we maintain authorship credit for Azavea, but this is the contact info that appears on PyPi and in Anaconda, so we should make sure it directs people to the right support email.
* Should we use [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) to require Python >=3.6 since we don't test against anything earlier?

**Comment by lossyrob** [comment]
Some of this is left over during the move from the azavea org to stac-utils, so changing the Gitter and the package author is good. The author should be stac-utils, same as stactools (https://github.com/stac-utils/stactools/blob/master/setup.py#L70-L71). 

As you mentioned, the gitter channel doesn't get traffic now - perhaps we switch the gitter batch to point to the SpatioTemoral Asset Catalog/python room, as that's where most pystac discussion happens anyway? Badge here: [![Gitter](https://badges.gitter.im/SpatioTemporal-Asset-Catalog/python.svg)](https://gitter.im/SpatioTemporal-Asset-Catalog/python?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

I also liked your suggestion in the STAC gitter around setting up GitHub discussion for this project...haven't used that feature yet but perhaps would be a good place to direct some issues that are submitted that are more around discussion topics and have a distinction between issues with specific goals and things like RFC's.

**Comment by duckontheweb** [comment]
Closed via #409
