### ISSUE TITLE
Using cwd for tempfile.TemporaryDirectory makes assumptions that are not always valid

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#418]
I test in an environment where the source this is read only and the test data is in a [CAS](https://en.wikipedia.org/wiki/Content-addressable_storage).  Making assumptions about the current working directory is trouble.  At least make this setting of the current working directory be dependent on being on windows or in the github CI.  Forcing a user's test environment means I'm forever having the chase and patch out the changes.  Happy to work with anyone for a solution that works for all.

This in tests/utils/__init__.py:

```python
# Use suggestion from https://github.com/python/mypy/issues/5264#issuecomment-399407428
# to solve type errors.
def get_temp_dir() -> "TemporaryDirectory_Type[str]":
    """In the GitHub Actions Windows runner the default TMPDIR directory is on a
    different drive (C:\\) than the code and test data files (D:\\). This was causing
    failures in os.path.relpath on Windows, so we put the temp directories in the
    current working directory instead. There os a "tmp*" line in the .gitignore file
    that ignores these directories."""
    return TemporaryDirectory(dir=os.getcwd())
```

Causes a failure trying to write in read-only storage.

```
suffix = '', prefix = 'tmp'
dir = '/build/work/f4eecd22e8cbe59830e035d545bf935d2afc/google3/runfiles/google3/third_party/py/pystac'

    def mkdtemp(suffix=None, prefix=None, dir=None):
        """User-callable function to create and return a unique temporary
        directory.  The return value is the pathname of the directory.
    
        Arguments are as for mkstemp, except that the 'text' argument is
        not accepted.
    
        The directory is readable, writable, and searchable only by the
        creating user.
    
        Caller is responsible for deleting the directory when done with it.
        """
    
        prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
    
        names = _get_candidate_names()
        if output_type is bytes:
            names = map(_os.fsencode, names)
    
        for seq in range(TMP_MAX):
            name = next(names)
            file = _os.path.join(dir, prefix + name + suffix)
            try:
>               _os.mkdir(file, 0o700)
E               PermissionError: [Errno 13] Permission denied: '/build/work/f4eecd22e8cbe59830e035d545bf935d2afc/google3/runfiles/google3/third_party/py/pystac/tmpf_aoq0zi'
```

**Comment by duckontheweb** [comment]
That's a fair point, @schwehr this was a pretty clumsy solution on my part at the end of a long slog just trying to get things to work on Windows 😄 . 

According to the [Python `tempfile` docs](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) we should be able to leave `dir=None` and use an environment variable to set the default temporary directory location:

> If dir is not `None`, the file will be created in that directory; otherwise, a default directory is used. The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the TMPDIR, TEMP or TMP environment variables.

I tried setting those variables initially, but it did not seem to have any effect. Maybe it's worth experimenting with that some more to see if someone can get it to work, in which case we could go back to just using `TemporaryDirectory` directly in all of the tests. If that doesn't work, we could always define our own environment variable and handle it through some custom logic.
