### ISSUE TITLE
How to set absolute href with 'http'?

### ISSUE THREAD

**Issue by nikkopante** [stac-utils/pystac#425]
Hi, I am generating STAC jsons on local computer. I want to set an absolute endpoint with `URL` as href. However I cannot save it.
```
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'http:'
```

```
URL = 'http://sample-stac.s3-website-us-east-1.amazonaws.com/sample/stac'
for image in images:
	...
	item = pystac.Item(
                id=id_name,
                 geometry=footprint,
                 bbox=bbox,
                 datetime=date_time_obj,
                 properties={})
	...
	item_href = '{url}/stac/{capture_name}/{capture_name}.json'.format(url=URL, capture_name=id_name)
        item.set_self_href(item_href)
        item.resolve_links()
        item.validate()
        catalog.add_item(item)


catalog_href = '{url}/catalog.json'.format(url=URL)
catalog.set_self_href(catalog_href)
catalog.resolve_links()
catalog.validate()
catalog.save(catalog_type=pystac.CatalogType.ABSOLUTE_PUBLISHED)
```

How can I use an endpoint to set it as hrefs while using the local computer?

I have tried putting
```
STAC_IO.write_text_method = my_write_method
```
from [STAC_IO](https://pystac.readthedocs.io/en/latest/concepts.html#using-stac-io)

**Comment by duckontheweb** [comment]
@cnpante12 Happy to try to help with this. A couple of questions for you...

Are you hoping to save the catalog to your local drive, or do you want to save it to the `http://sample-stac.s3-website-us-east-1.amazonaws.com/sample/stac/stac/{capture_name}/{capture_name}.json` location in the URL?

Also, what version of PySTAC are you using?

**Comment by cnpante12** [comment]
Thank you @duckontheweb.
I am using the latest version of STAC. I want to save the catalog in the local drive but I want the href to be `http://sample-stac.s3-website-us-east-1.amazonaws.com/sample/stac/stac/{capture_name}/{capture_name}.json`. I am doing this because I will manually upload the static files in S3.

**Comment by duckontheweb** [comment]
@cnpante12 If you are still looking for a solution to this, you should be able to accomplish this using the `dest_href` argument to `Catalog.save`. In your example above, this would involve changing the final line from...

```python
catalog.save(catalog_type=pystac.CatalogType.ABSOLUTE_PUBLISHED)
```

...to...

```python
local_path = ...  # This should be a path to a directory on your local machine
catalog.save(catalog_type=pystac.CatalogType.ABSOLUTE_PUBLISHED, dest_href=local_path)
```
