### ISSUE TITLE
RFC: Remove deprecated STAC_IO class

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac#431]
After #309 the [`STAC_IO`](https://github.com/stac-utils/pystac/blob/8946c9b192e20f53b75196915bb078c91954ae76/pystac/stac_io.py#L262) class was deprecated in favor of [`StacIO`](https://github.com/stac-utils/pystac/blob/8946c9b192e20f53b75196915bb078c91954ae76/pystac/stac_io.py#L36). The v1.0.0 release seems like a good time to remove `STAC_IO` from the code base so we are not starting a new major release with a deprecated feature.

I propose that we add more specific deprecation notices to `STAC_IO` and its methods in v1.0.0-rc.1 that indicate its removal in v1.0.0, and that we remove the class entirely in v1.0.0.

The purpose of this issue is to get  feedback on this proposal. It would also be good to hear about any changes that need to be made to `StacIO` to make the transition smoother, especially for maintainers of other libraries that have PySTAC as a dependency.

cc: @gadomski @matthewhanson @lossyrob

**Comment by matthewhanson** [comment]
I'm +1 on not having a deprecated class in a v1.0.0 release.  I think that any dependent library, when updating it's dependency to PySTAC 1.0.0, should be updated itself to use the new StacIO class.
