### ISSUE TITLE
Additional helper methods to remove assets from an item

### ISSUE THREAD

**Issue by stark525** [stac-utils/pystac#438]
**Version**: 1.0.03b

**Feature Description**:
It would be great to have a way to 1. drop all assets associated with an [Item](https://pystac.readthedocs.io/en/latest/api.html#item), or 2. filter items to drop.

**Example use-case for feature**:
I am manipulating assets, processing from level 1 -> level 2, and before uploading to a new collection I would like to re-use the bulk of the original STAC item.

1. I may wish to drop all assets and cherrypick only those I care about. 

2. Or I may wish to keep specific assets (e.g. thumbnail), but drop the rest / or keep specific asset types (all .TIF).

**Comment by gadomski** [comment]
These should both be relatively simple to do on your own.

```python
from pystac import Item

item = Item.from_file("tests/data-files/item/sample-item.json")
print(item.assets)

# Drop all assets
item.assets = {}
print(item.assets)

# Filter assets
item = Item.from_file("tests/data-files/item/sample-item.json")
item.assets = dict(
    (key, asset) for key, asset in item.assets.items() if key != "thumbnail"
)
print(item.assets)
```

Output:

```text
{'analytic': <Asset href=http://cool-sat.com/catalog/CS3-20160503_132130_04/analytic.tif>, 'thumbnail': <Asset href=http://cool-sat.com/catalog/CS3-20160503_132130_04/thumbnail.png>}
{}
{'analytic': <Asset href=http://cool-sat.com/catalog/CS3-20160503_132130_04/analytic.tif>}
```

I'm closing as not planned, but please re-open if you think that we should add convenience functions to PySTAC to support these use-cases.
