### ISSUE TITLE
Empty Codecov reports because of "Github API rate limit"

### ISSUE THREAD

**Issue by l0b0** [stac-utils/pystac#444]
I'm seeing empty Codecov reports like [this one](https://github.com/stac-utils/pystac/pull/420#issuecomment-861102360). When clicking on the coverage map I get to a [page](https://app.codecov.io/gh/stac-utils/pystac/compare/420) with the following message:

>  Unauthorized
>
> Github API rate limit error: Forbidden Check on Codecov's status or see our docs for common support.
> 
> Error 403

**Comment by duckontheweb** [comment]
I have not seen these lately and I think they were an issue on the Codecov side anyway. Closing for now, but we can re-open if this becomes an issue again.
