### ISSUE TITLE
Update the quickstart in the docs

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#462]
The quickstart is currently out of date. We should remove the STAC_IO references completely (HTTP reading is now supported out of the box, has been for a bit), uses the old extension methods, and need to point to a new catalog - the current example is 0.6.

**Comment by duckontheweb** [comment]
@matthewhanson @lossyrob Any thoughts on what would be a good 1.0.0 static catalog to use in our quickstart example?

**Comment by scottyhq** [comment]
I think a fully contained static STAC example catalog would be really valuable and could be used for such a quickstart (and other projects). I made a comment here https://github.com/stac-utils/stac-examples/issues/1, but am not sure whether to try to modify those existing examples or just start fresh. 

So many existing tests and examples have fake URLs for assets or point to externally hosted data (and as we've seen with the original landsat8 bucket on AWS those URLs may eventually disappear). Yes, if you bake real-world assets into the repository it would be 100's of MB, but if only the metadata files change with STAC version updates it wouldn't run the risk of ballooning too much.
