### ISSUE TITLE
Add documentation on how to migrate STACs to latest version

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#463]
As noted in [this comment](https://github.com/stac-utils/pystac/issues/441#issuecomment-864115115), it would be good to have a clear guide on how to use PySTAC to migrate STACs, both now (migrating to 1.0) and in the future.

**Comment by duckontheweb** [comment]
#687 [added a section](https://github.com/stac-utils/pystac/blob/f1051f999d1930fa6d4295bbb632597fdcca2116/docs/concepts.rst#stac-spec-version-support) to the Concepts docs on STAC spec version support and the fact that catalogs are automatically updated using PySTAC.

@lossyrob @scottyhq Do you think we need more detail on this somewhere?

**Comment by duckontheweb** [comment]
Closing this since it was addressed as part of #687. If anyone thinks we need more guidance on this topic feel free to comment and re-open.
