### ISSUE TITLE
Deprecating support for older Python 3 versions

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac#474]
We currently test against and allow installation on Python >=3.6. If we want to drop support for any Python 3 versions, we should do it prior to the 1.0.0 release. For instance, if we think we may want to take advantage of `dataclasses` we could restrict support to Python >=3.7, or if we wanted to take advantage of `functools.cached_property` we could restrict support to Python >=3.8 so that we don't need to use backports. 

This issue is not meant to advocate for dropping Python 3.6, but rather to open up a discussion prior to the stable release so that we make an informed decision. 

Personally I am +0 on dropping support for Python 3.6 or 3.7. I think there is a good chance that users are still using those versions, and we do not have a burning need to use features introduced in later versions.

**Comment by TomAugspurger** [comment]
I don't know what percent of pystac users are also using NumPy, but many libraries in the scientific Python ecosystem have adopted [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) which provides clear rules on when projects should drop older versions of Python (and NumPy)

**Comment by duckontheweb** [comment]
> I don't know what percent of pystac users are also using NumPy, but many libraries in the scientific Python ecosystem have adopted [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) which provides clear rules on when projects should drop older versions of Python (and NumPy).

Thanks for sharing that @TomAugspurger! Based on that timeline we could drop support for 3.6 in the 1.0.0 release, but should support 3.7 until the beginning of 2022.
