### ISSUE TITLE
Test both with and without orjson

### ISSUE THREAD

**Issue by l0b0** [stac-utils/pystac#475]
Currently the test suite installs the optional dependency orjson. To make sure pystac also works without orjson we should run the test suite both with and without it. We can use `coverage --append` to merge the coverage information from both runs.

**Comment by gadomski** [comment]
We added CI tests w/o **orjson** in #348. Coverage is not merged -- @l0b0 how critical would you consider merging that coverage data? Can we close this issue?

**Comment by l0b0** [comment]
Merging the coverage (it's [easy](https://github.com/linz/geostore/blob/480449b12fed52e6c0f8f0e68ef01be54b8b939f/.github/workflows/test.yml#L143-L144)) would give a more accurate coverage metric, and would be necessary to eventually reach 100%.
