### ISSUE TITLE
Make sure all test data is local

### ISSUE THREAD

**Issue by l0b0** [stac-utils/pystac#494]
Some tests seem to be [pulling files from for example https://cmr.earthdata.nasa.gov/stac/](https://cmr.earthdata.nasa.gov/stac/), which is causing false positives and slowing down test runs. We should probably store a copy of such data locally or create minimal equivalent test data explicitly for the relevant purpose, to avoid these issues.

**Comment by gadomski** [comment]
Will be solved in conjunction with #949.
