### ISSUE TITLE
Tests trying to loop more than once through iterators

### ISSUE THREAD

**Issue by l0b0** [stac-utils/pystac#502]
`test_get_sources` and `test_map_items_multiple` try to do something like this:

```python
items = cat.get_all_items()
item_ids = set([i.id for i in items])

for li in items:
    # assert some stuff
```

The problem is that `get_all_items` returns an `Iterable`, which means it can normally only be looped over *once.* Because of this, the contents of `for li in items:` are never reached (see the coverage report). I tried to fix this by changing the first line to `items = list(cat.get_all_items())` (which can be looped over more than once) in `test_get_sources`, but that resulted in a different issue:

```
ERROR: test_get_sources (tests.extensions.test_label.LabelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/victor/dev/pystac/tests/extensions/test_label.py", line 141, in test_get_sources
    if LabelExtension.ext(li).has_extension:
  File "/home/victor/dev/pystac/pystac/extensions/label.py", line 709, in ext
    cls.validate_has_extension(obj)
  File "/home/victor/dev/pystac/pystac/extensions/base.py", line 138, in validate_has_extension
    raise pystac.ExtensionNotImplemented(
pystac.errors.ExtensionNotImplemented: Could not find extension schema URI https://stac-extensions.github.io/label/v1.0.0/schema.json in object.
```

This is sufficiently obscure that I'm not sure what the solution is.

**Comment by gadomski** [comment]
This issue was masking a improper call bug that was caught by my fixes in #909. Once #909 is merged, we can fix this one.
