### ISSUE TITLE
RFC: Passing around mutable references

### ISSUE THREAD

**Issue by l0b0** [stac-utils/pystac#541]
`Collection.get_assets` and `Item.get_assets` return `dict(self.assets.items())`. This does a shallow copy of the assets:

```python
>>> assets = {"a": []}
>>> bar = dict(assets.items())
>>> assets["a"].append("entry")
>>> bar
{'a': ['entry']}
```

I wonder if the intention was `deepcopy(self.assets)` or simply `self.assets` instead?

There are also a few other places where it does similar things, like `map(apply_asset_mapper, item.assets.items())`, which I'm even less sure about. But I would expect the intent to be, in general, either always or never return deep copies of anything which could possibly contain mutable references.

**Comment by gadomski** [comment]
xref https://github.com/stactools-packages/cop-dem/issues/11#issuecomment-1472243905
