### ISSUE TITLE
RFC: Use annotated tags for releases

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac#550]
`git describe`, by default, only checks annotated tags. It can be nice to check what version you're based upon by a quick run of `git describe`, but at e.g. 12eff70 this doesn't work:

```bash
$ git --no-pager show -s --oneline
12eff70 (HEAD -> main, origin/main) Merge pull request #544 from stac-utils/dependabot/pip/orjson-3.6.0
$ git describe
v0.5.0-RC1-919-g12eff70
```

To get the correct descriptor you need to use `--tags`:

```bash
(pystac) ➜  pystac git:(main) git describe --tags
v1.0.0-rc.3-6-g12eff70
```

**Comment by duckontheweb** [comment]
Thanks for this @gadomski. We've started using annotated tags for the last couple of releases and will plan on continuing to do this in the future.
