### ISSUE TITLE
Self HREFs are not always absolute

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac#571]
In the documentation for `STACObject.get_self_href`, it states that the returned HREF will be absolute: https://github.com/stac-utils/pystac/blob/76ef6a3b9bc3412cfcbc7f502d8fc1f56310b779/pystac/stac_object.py#L145-L164

However, no work is done to ensure that the self href is absolute, as demonstrated by this [failing test](https://github.com/gadomski/pystac/commit/d72605fd181b2fe6c7d047426df151e481d1f001):

```python
def test_relative_self_href(self) -> None:
    self.item.add_link(pystac.Link("self", "a/relative/path/item.json"))
    # this fails
    self.assertEqual(
           self.item.get_self_href(), os.path.abspath("a/relative/path/item.json")
    )
```

This is true for objects read via, e.g. `pystac.read_file` as well. Should the returned self HREF be resolved to an absolute HREF as best as possible, or should we just return `None`?

**Comment by lossyrob** [comment]
Fixed by #574
