### ISSUE TITLE
pystac.extensions.file.MappingObject doesn't work

### ISSUE THREAD

**Issue by jamesvrt** [stac-utils/pystac#605]
`pystac.extensions.file.MappingObject` is broken and/or the docs should not specify to use it. An example:

```python
from pystac.extensions.file import FileExtension, MappingObject

FILE_SIZE = 100
VALUES = {
    1: "Temperate or sub-polar needleleaf forest",
    2: "Sub-polar taiga needleleaf forest",
    3: "Tropical or sub-tropical broadleaf evergreen forest",
...
}

values: List[MappingObject] = [
    MappingObject.create(values=[i], summary=s) for i, s in VALUES.items()
]

file_ext = FileExtension.ext(data_asset, add_if_missing=True)
file_ext.apply(size=FILE_SIZE, values=values)
```
results in
```
TypeError: Object of type MappingObject is not JSON serializable
```
when saving the STAC. The following change is a viable workaround:
```python
values: List[Any] = [
    dict(values=[i], summary=s) for i, s in VALUES.items()
]
```

**Comment by lossyrob** [comment]
The fix is to make the `values` setter [here](https://github.com/stac-utils/pystac/blob/main/pystac/extensions/file.py#L187) "unbox" the MappingObject in a similar fashion as is done [here](https://github.com/stac-utils/pystac/blob/main/pystac/extensions/label.py#L542)
