### ISSUE TITLE
Quickstart and Tutorial documentation out of date

### ISSUE THREAD

**Issue by yeelauren** [stac-utils/pystac#606]
Hi there, new to STAC and trying to learn but hitting some roadblocks with the documentation.

 I can’t get the quickstart tutorials to run or produce the same outputs that are in the documentation - is the documentation up to date? 
 
Some lines of code gave me back errors or the meta data returned was blank when the example showed a different result for the same URL. I cloned the repo and installed it directly and still had similar issues.

I have stactools 0.2.1 and pystac 1.1.0 python 3.8.8 on MacOS.

```
#this doesn't work

from urllib.parse import urlparse
import requests
from pystac import STAC_IO

def requests_read_method(uri):
    parsed = urlparse(uri)
    if parsed.scheme.startswith('http'):
        return requests.get(uri).text
    else:
        return STAC_IO.default_read_text_method(uri)
```

```
STAC_IO.read_text_method = requests_read_method
ImportError: cannot import name 'STAC_IO' from 'pystac' (/opt/anaconda3/lib/python3.8/site-packages/pystac/__init__.py)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8f6ab85a192b> in <module>
      3 from urllib.parse import urlparse
      4 import requests
----> 5 from pystac import STAC_IO
      6 
      7 def requests_read_method(uri):

ImportError: cannot import name 'STAC_IO' from 'pystac' (/opt/anaconda3/lib/python3.8/site-packages/pystac/__init__.py)

```

It looks like `StacIO` exists in __init__ but not `STAC_IO`

Additionally, the jupyter notebooks aren't reproducible e.g. `cat = pystac.Catalog.from_file('example-catalog/catalog.json')
cat.describe()` does not yield that same results in the docs.

#462

**Comment by croros** [comment]
Was about to post on this thread because I couldn't figure out how read_text works in the new version but I think I figured it out. Now you have to instantiate an DefaultStacIO object to actually read text:
`mystac = pystac.stac_io.DefaultStacIO()
print(mystac.read_text(mtl_url))
`

**Comment by luipir** [comment]
I faced the same problem. Seems the default/lastest installed version of pystac e.g. 1.1 based ON STAC 1.0 do not have documentation and tutorial updated.
My temporary solution is to use tests and ipython instrospection to have a guide how to implement.
BTW follow tests do not garantee to create a stac that pass validation :/
