### ISSUE TITLE
Bubble up exception in validators.resolve_from_url

### ISSUE THREAD

**Issue by podosinovik** [stac-utils/pystac#622]
So that I don't bury the (causal but not related) lead, the geojson.org schemas are unreachable (e.g. https://geojson.org/schema/Feature.json).

I discovered this when validating a pystac Item (pystac 1.1.0). The exception that I _correctly_ saw was:

```
File ".../python3.9/site-packages/jsonschema/validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: HTTP Error 404: Not Found
```

However, the specific URL is nowhere to be found in the exception. It would be really useful to have this information bubbled up in `exc` so that the developer doesn't have to go digging through the debug stack.

Thanks!

**Comment by podosinovik** [comment]
The schema issue has already been captured in the geojson repo: https://github.com/geojson/schema/issues/29

**Comment by gadomski** [comment]
If **requests** is present on the system, **jsonschema** doesn't propagate the problematic URL. I've opened https://github.com/python-jsonschema/jsonschema/pull/1050 to fix, and consider that a blocker to fixing this issue. I've got a WIP branch that has some test infrastructure we can use once/if **jsonschema** is updated: https://github.com/stac-utils/pystac/tree/issues/622-better-exceptions.

**Comment by gadomski** [comment]
Well, looks like **jsonschema** is going through a major overhaul: https://github.com/python-jsonschema/jsonschema/pull/1050#issuecomment-1440602758. All the more reason to hold off on any changes/fixes until that lands.
