### ISSUE TITLE
Update sphinx theme

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/pystac#635]
[bikeshedding warning]

Are people attached to the current sphinx theme? I find it a bit hard to read, especially the [API docs](https://pystac.readthedocs.io/en/latest/api.html).

https://sphinx-themes.org/#themes has a nice gallery of themes to choose from. I would recommend one of [Furo](https://sphinx-themes.org/sample-sites/furo/) or the [PyData](https://sphinx-themes.org/sample-sites/pydata-sphinx-theme/) themes.

**Comment by duckontheweb** [comment]
I'm in favor of changing the theme, I also find the current one hard to read.

Between Furo and PyData my preference would be PyData (again, I just find it a bit more readable), but I'm open to either.
