### ISSUE TITLE
Add a `stac_io` argument in `Catalog.save`?

### ISSUE THREAD

**Issue by fnattino** [stac-utils/pystac#666]
It is nice how the STAC I/O has been refactored, with the possibility for the user to provide customised `StacIO` instances as argument to `StacObject.save_object` (or `ItemCollection.save_object`).

But shouldn't the catalog `Catalog.save` method also accept a `stac_io` argument to optionally specify the `StacIO` to recursively write out all children and items?

If you agree, I would be happy to contribute with a PR!

**Comment by thomafred** [comment]
`StacIO`'s abstract member functions `read_text` and `write_text` are called by `read_stac_object` and `save_json` respectively. This allows for custom file formats, but is limiting as it does not enable the ability to use alternative protocols. This is actually mentioned in the docs:

```
# stac_io.py:324
This implementation uses :func:`open` and therefore can only write to the local
file system.
```

Personally, I think that `StacIO` should only contain two abstract functions:

```python
# Essentially the same as current implementation
def read_stac_object(
    self,
    source: Union[str, "Link_Type"],
    root: Optional["Catalog_Type"] = None,
    *args: Any,
    **kwargs: Any,
) -> "STACObject_Type"

def write_stac_object(
        self,
        dest: Union[str, "Link_Type"],
        stac_object: "STACObject_Type",
        *args: Any,
        **kwargs: Any,
    ) -> None
```
This would create explicit entry-points for IO-operations and enable develops to easily create custom integrations for APIs and custom file protocols.

**Comment by duckontheweb** [comment]
> It is nice how the STAC I/O has been refactored, with the possibility for the user to provide customised `StacIO` instances as argument to `StacObject.save_object` (or `ItemCollection.save_object`).
> 
> But shouldn't the catalog `Catalog.save` method also accept a `stac_io` argument to optionally specify the `StacIO` to recursively write out all children and items?
> 
> If you agree, I would be happy to contribute with a PR!

@fnattino I would support adding a `stac_io` argument to `Catalog.save` and would be happy to review a PR! I agree that needing to read and write using different protocols/file systems is a common enough use case that we should make it convenient to do.
