### ISSUE TITLE
STAC API not supported

### ISSUE THREAD

**Issue by thomafred** [stac-utils/pystac#682]
I have been playing around withe the [stac-fastapi](https://github.com/stac-utils/stac-fastapi) using pystac. Unfortunately it does not seem like this is not supported.

From what I can see, there are a few hurtles to be crossed before this can work:

* There is no [`StacIO`](https://github.com/stac-utils/pystac/blob/main/pystac/stac_io.py#L39) implementation that supports writing to a STAC API.
* The href-handling assumes a local file-system:
   - https://github.com/stac-utils/pystac/blob/main/pystac/catalog.py#L615
   - https://github.com/stac-utils/pystac/blob/main/pystac/catalog.py#L237
   - https://github.com/stac-utils/pystac/blob/main/pystac/catalog.py#L283
   - https://github.com/stac-utils/pystac/blob/main/pystac/catalog.py#L595

To me it does not seem like a lot of work for pystac to work with the stac-fastapi, and I would love to see this happen. Can contribute with a PR, but may need some guidance.

**Comment by duckontheweb** [comment]
The [pystac-client library](https://github.com/stac-utils/pystac-client) is where we have been adding support for interacting with STAC API implementations like stac-fastapi. PySTAC itself has been more focused around providing support for interacting with the basic STAC types described in the core STAC spec and in any STAC Extensions that exist in the [`stac-extensions` GitHub org](https://stac-extensions.github.io/) ([#371(comment)](https://github.com/stac-utils/pystac/issues/371#issuecomment-854299086) has some thoughts on this distinction). Part of the reasoning behind this was that it seemed to make sense to introduce additional dependencies (like `requests`) when interacting with a STAC API and we wanted to keep the number of dependencies in PySTAC to an absolute minimum.

**Comment by thomafred** [comment]
Cool. I was not aware of `pystac-client`.

From what I can gather, it does not seem like this library supports writing to the API?

**Comment by duckontheweb** [comment]
@matthewhanson and @philvarner can probably comment on this more, but I believe the [Transactions Extension](https://github.com/radiantearth/stac-api-spec/blob/master/ogcapi-features/extensions/transaction/README.md) would be the mechanism for writing to an API and I'm not sure if there is any specific support for that in `pystac-client`. If not, it's probably worth opening an issue in that repo to request support.

**Comment by duckontheweb** [comment]
Closing this, but feel free to open issues on `pystac-client` if there are any feature requests related to that project.
