### ISSUE TITLE
Incorrect Link for PySTAC Introduction Tutorial "Docs Version"

### ISSUE THREAD

**Issue by KennSmithDS** [stac-utils/pystac#711]
The URL for the "Docs Version" of the PySTAC Introduction tutorial notebooks is incorrect in both the stable release of the docs as well as the new theme via #687.

The GitHub Version link is correct:

- https://github.com/stac-utils/pystac/tree/HEAD/docs/tutorials/pystac-introduction.ipynb

But the Docs Version link goes to SpaceNet:

- https://pystac.readthedocs.io/en/latest/tutorials/pystac-spacenet-tutorial.html

**Comment by duckontheweb** [comment]
Closed via #719
