### ISSUE TITLE
Collection assets removed on clone()

### ISSUE THREAD

**Issue by cholden-ag** [stac-utils/pystac#747]
Hello! First thanks for this wonderful library, it's been super helpful

I might be misunderstanding, but I think there is an issue with Collections losing their assets when you run `.clone()` because the attribute is not carried over when constructing a new instance. I saw some discussion about placing asset info in the `Collection.extra_fields` attribute (ref https://github.com/stac-utils/pystac/issues/293) but my understanding is that Collections now support having assets (e.g., there's a `Collection.add_asset`)

It looks to me like the asset attribute needs to be included in this call,
https://github.com/stac-utils/pystac/blob/main/pystac/collection.py#L556-L568
but was maybe omitted as the STAC spec evolved.

Example,
```python
>>> import pystac
>>> coln = pystac.read_file("https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-8-c2-l2")
# nice thumbnail!
>>> coln.assets
{'thumbnail': <Asset href=https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/landsat.png>}
# works
>>> coln.to_dict()['assets']
{'thumbnail': {'href': 'https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/landsat.png', 'type': 'image/png', 'title': 'Landsat 8 C2', 'roles': ['thumbnail']}}
# broken
>>> coln.clone().assets
{}
```

If this makes sense I'm happy to add a PR with a fix and tests

**Comment by duckontheweb** [comment]
@cholden-ag Thanks for the detailed bug report, and for tracking down the issues. I would happily review a PR with tests!

In `Item.clone` we handle transferring assets by [calling `item.add_asset(...)` after the new `Item` is created](https://github.com/stac-utils/pystac/blob/8509f4705659cccdefe347cf222d0dcf5e402cec/pystac/item.py#L356-L357), so I think we should follow the same pattern for `Collection.clone`.

Alternatively, I would support adding an `assets` argument to both `Item.__init__` and `Collection.__init__`. I'm not sure why we don't include that as an optional argument already, but it seems like it would be nice to be able to create Items and Collections with assets in a single line.

**Comment by duckontheweb** [comment]
@cholden-ag Do you have bandwidth to put in a PR for this issue in the near future?
