### ISSUE TITLE
Support FlatGeobuf as media_type

### ISSUE THREAD

**Issue by ashiklom** [stac-utils/pystac#763]
[FlatGeobuf](https://flatgeobuf.org/) is an awesome, performant open-source alternative to ESRI ShapeFiles, GeoJSON, etc. for vector data. I am proposing the addition of a `pystac.MediaType.FLATGEOBUF` that resolves to `"application/flatgeobuf"`.

At least, I'm assuming that's the correct MIME Type — that's what's returned by:

```
curl https://flatgeobuf.septima.dk/population_areas.fgb --head
```

If all I have to do is just add a line [here](https://github.com/stac-utils/pystac/blob/main/pystac/media_type.py#L4) then I can submit a PR. But I'm not sure if there's something more involved in ensuring FlatGeobuf support.

**Comment by TomAugspurger** [comment]
Looking at https://github.com/flatgeobuf/flatgeobuf/discussions/112, I don't think "application/flatgeobuf" is "official" :/ We'd probably want to wait on that, but I'm not sure.

**Comment by m-mohr** [comment]
The COG media type for example is also not official yet, but I think we can follow what the community uses until it is official. Adding it to PySTAC may actually help to promote a single media type and not everyone has to search and find one (result might differ), so I'm +1 on adding it.

**Comment by gadomski** [comment]
@ashiklom if you're willing to make a PR, that would help force an up/down vote on the issue.

@m-mohr what's the skinny on `profile=cloud-optimized`? Should that be included in the flatgeobuf media type?

**Comment by gadomski** [comment]
I'm not sure, I'm just reading up on it myself. It is based on http://google.github.io/flatbuffers/, which appears to be "cloud optimized" (for some value of "cloud optimized") itself. So my guess is that it's a geospatial specialization of an already-cloud-optimized format. But @ashiklom (or others) should chime in with Actual Knowledge™.

**Comment by m-mohr** [comment]
Yeah, if it is already cloud-optimized you don't need the profile.
