### ISSUE TITLE
DatacubeExtension.apply is unaware of variables

### ISSUE THREAD

**Issue by itcarroll** [stac-utils/pystac#781]
The recent addition (#699) of the variable setter did not add an accompanying change to the `DatacubeExtension.apply` method. As a result, you cannot set dimensions and variables in one swoop with the apply method. The [documentation implies](https://pystac.readthedocs.io/en/latest/concepts.html#accessing-extension-functionality) that `apply` should allow you to pass in extension properties.

Additionally, there is no test for the apply method, so adding one seems appropriate now and will help with #324.

**Comment by itcarroll** [comment]
Why does the `DatacubeExtension.variables` getter return a new dictionary, rather than the result of `self._get_property`? This quietly breaks `ext_item.variables.pop`, which will return a name but not remove the variable from `ext_item`. Feature or bug?

Trying to understand so I can re-write the test_apply_variables method I've introduced in #782 if necessary (or fix a bug).

**Comment by duckontheweb** [comment]
The result of `self._get_property` is always going to be a "native" Python type, but the return type of the getter methods often include PySTAC-specific classes. In this case, `self._get_property` is essentially returning a type of `Dict[str, Dict[str, Any]]`, but the getter needs to return a type of `Dict[str, Variable]`, so we use dictionary comprehension to convert the `Dict[str, Any]` to a `Variable`.
