### ISSUE TITLE
Update DataCube Extension to the latest version (support in assets)

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/pystac#856]
The data cube extension is available in 2.1.0 and now supports fields also in assets. It would be nice to support this. 

----

Original post:

I'm trying to use the DataCube extension in PySTAC, but I'm struggling:

```py
        asset = Asset.from_dict({...})
        item.add_asset("netcdf", asset)
        dc = DatacubeExtension.ext(asset, add_if_missing=True)
        for key, dim in dataset.dimensions.items():
            dc.dimensions[dim.name] = AdditionalDimension({...})
        for key, var in dataset.variables.items():
            dc.variables[var.name] = Variable({...})
```

I'm getting: `<AssetDatacubeExtension Item id=tests/data-files/OR_GLM-L2-LCFA_G16_s20203662359400_e20210010000004_c20210010000030.ncdoes not have required property cube:dimensions`

How is it meant to be used? Is this a bug?

**Comment by constantinius** [comment]
@m-mohr It looks like this is also an issue when used with `Collections` and `Items`. I also found out how it seems like it is meant to be used: the `dimensions` should be treated as immutable, and must be set to the `DatacubeExtension` as a whole, and not added piece wise. This works for me (both for Asset and Item):

```python
datacube: DatacubeExtension

dimensions = {}

dimension = HorizontalSpatialDimension({
    ...
})
dimensions[name] = dimension

datacube.dimensions = dimensions
```

I think it is way to easy to get this wrong. At least some documentation is missing in how to use it the intended way.

**Comment by gadomski** [comment]
Datacube is now at v2.2.0.
