### ISSUE TITLE
Switch sphinx-panels -> sphinx-design

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac#868]
The `sphinx-panels` project is no longer actively maintained and will probably not update to support Sphinx 5.x. This is blocking our upgrade to Sphinx 5 (#824). We should switch to `sphinx-design` instead (as recommended in the `sphinx-panels` README and executablenotebooks/sphinx-panels#80).

**Comment by jsignell** [comment]
I can take this one.
