### ISSUE TITLE
RFC: Allow `validate_all` to return all issues with a STAC catalog

### ISSUE THREAD

**Issue by john-dupuy** [stac-utils/pystac#887]
Right now the behavior of `validate_all` and `Catalog.validate_all` is to return only the first problem it encounters in a STAC catalog. 

It would be nice if there was some flag we could set (or alternate method we could use) so that we could get a list of all the issues that were discovered.

`jsonschema` provides a way to do this via [`iter_errors`](https://python-jsonschema.readthedocs.io/en/latest/api/jsonschema/protocols/?highlight=iter_errors#jsonschema.protocols.Validator.iter_errors) and I'm wondering if something like that could work here. 

Also not sure if there is some way to do this already as I'm quite new to `pystac`. Happy to take this on as a first issue if the team thinks it's appropriate.

**Comment by gadomski** [comment]
> Happy to take this on as a first issue if the team thinks it's appropriate.

I think it's a reasonable suggestion, and a PR would be welcome!
