### ISSUE TITLE
pystac is now on conda-forge!

### ISSUE THREAD

**Issue by rsignell-usgs** [stac-utils/pystac#89]
Thanks to @ocefpaf, pystac is now on conda-forge: https://anaconda.org/conda-forge/pystac

Created via the recipe in: https://github.com/conda-forge/pystac-feedstock

**Comment by lossyrob** [comment]
Thank you Rich!

**Comment by duckontheweb** [comment]
@rsignell-usgs @ocefpaf Would either of you be interested in maintaining that feedstock as we release new versions to PyPi? We have a few 1.0.0-beta.* releases that have come out recently and are planning on a 1.0.0-rc.1 release early next week.

**Comment by ocefpaf** [comment]
> @rsignell-usgs @ocefpaf Would either of you be interested in maintaining that feedstock as we release new versions to PyPi? We have a few 1.0.0-beta.* releases that have come out recently and are planning on a 1.0.0-rc.1 release early next week.

The conda-forge bot will handle stable releases. We usually don't ship dev/rc unless users ask for it. They are meant for testing and not for end user consumption. (Although PyPI made it easy for devs to publish them and now everybody uses them in production :-/)

**Comment by duckontheweb** [comment]
Sounds great. My experience creating conda recipes is pretty limited, so sorry if these questions are obvious...

- Are the `validation` and `orjson` dependencies installed as part of that recipe? If not, does conda have any way of optionally installing those as you would with pip/setuptools (e.g. `pip install "pystac[validation,orjson]"?
- Is there a way to include a link to the docs (https://pystac.readthedocs.io/en/latest/) in the `about` section?
- Maybe we should update the [`home`](https://github.com/conda-forge/pystac-feedstock/blob/77d82875e7417e0accb9a9af88e19d46b22098c5/recipe/meta.yaml#L36) field to point to the new repo location? GitHub redirects that URL already, which is fine, but it would probably be good for that to be up-to-date.

I can also put in a PR for those changes if you don't have time.

**Comment by ocefpaf** [comment]
> Sounds great. My experience creating conda recipes is pretty limited, so sorry if these questions are obvious...

NP
 
> * Are the `validation` and `orjson` dependencies installed as part of that recipe? If not, does conda have any way of optionally installing those as you would with pip/setuptools (e.g. `pip install "pystac[validation,orjson]"`?

They are not installed in the default package. Optional dependencies are something that does not make sense for an agnostic package manager like conda. What people do to emulate that is to create sub-packages like `pystac-core` with the default dependencies and `pystac` with the full list. Or, some people prefer the opposite, `pystac` has the default and `pystac-validation` and `pystac-orjson` with the optional. Most people go with the former b/c it is only two packages, a core and complete while the latter can blow up to hundreds of packages really quickly. 

> * Is there a way to include a link to the docs (https://pystac.readthedocs.io/en/latest/) in the `about` section?

Yes. I'll do that in the next iteration of the package.

> * Maybe we should update the [`home`](https://github.com/conda-forge/pystac-feedstock/blob/77d82875e7417e0accb9a9af88e19d46b22098c5/recipe/meta.yaml#L36) field to point to the new repo location? GitHub redirects that URL already, which is fine, but it would probably be good for that to be up-to-date.

Usually the autoupdater gets that too.

> I can also put in a PR for those changes if you don't have time.

Sure. If you don't mind please add your GitHub handle as a maintainer too :-)

**Comment by duckontheweb** [comment]
This all seems to be working as expected, so I'm closing this.
