### ISSUE TITLE
Microseconds in pystac.utils.datetime_to_str result truncated if microsecond in datetime object is 0

### ISSUE THREAD

**Issue by imanshafiei540** [stac-utils/pystac#927]
I'm trying to convert a `datetime` object to a `string`, so I'm using `pystac.utils.datetime_to_str` for this purpose.

```python
import datetime
from pystac.utils import datetime_to_str
dt = datetime.datetime(2022, 8, 23, 18, 31, 38, tzinfo=datetime.timezone.utc)
dt_string = datetime_to_str(dt)
```

The result of the above snippet is: `2022-08-23T18:31:38Z`
I'm trying to keep the consistency, so the result should be something like this: `2022-08-23T18:31:38.000000+00:00`

I found that in the `datetime_to_str` in the utils file, we're not using `timespec` for `isoformat`.

```python
import datetime
dt_string = datetime.datetime(2022, 8, 23, 18, 31, 38, tzinfo=datetime.timezone.utc).isoformat(timespec='microseconds')
```

The result: `2022-08-23T18:31:38.000000+00:00`

For my case, I wrote my own `datetime_to_str` function, but I wonder if there is a better way to do this. Also, if it's ok, maybe I could create a PR and add this ability. Btw, I'm not sure if my approach is the best way to achieve this goal or not.
Thanks.

**Comment by gadomski** [comment]
A pull request to add an optional `timespec` argument to `datetime_to_str` would be welcome! I do think the current behavior should remain the default behavior (e.g. `2022-08-23T18:31:38Z`)-- as far as I've seen, most real-world use-cases don't want/need resolutions down to the microsecond.
