### ISSUE TITLE
Retrieve MAXAR Open Data -  STACTypeError: JSON does not represent a STAC object

### ISSUE THREAD

**Issue by giswqs** [stac-utils/pystac#991]
I am trying to retrieve the [MAXAR Open Data Catalog](https://stacindex.org/catalogs/maxar-open-data-catalog-ard-format#/) using the the url  `https://maxar-opendata.s3.amazonaws.com/events/catalog.json`. However, I can't get it to work with pystac or pystac-client. What's the recommended way to read a stac catalog like this?

I noticed that the [stac-browser website](https://radiantearth.github.io/stac-browser/#/external/maxar-opendata.s3.amazonaws.com/events/catalog.json) was able to crawl the collections and items using the same catalog URL shown above. How can we do this using Python?

```python
import pystac
url = 'https://maxar-opendata.s3.amazonaws.com/events/catalog.json'
pystac.read_file(url)
```

> STACTypeError: JSON does not represent a STAC object.

```python
from pystac_client import Client
url = 'https://maxar-opendata.s3.amazonaws.com/events/catalog.json'
client = Client.open(url)
```

> ClientTypeError: Could not open Client (href=https://maxar-opendata.s3.amazonaws.com/events/catalog.json), expected type=Catalog, found type=None

**Comment by drwelby** [comment]
I build those catalogs, so let me know if I need to adjust anything.

**Comment by gadomski** [comment]
Looks like that endpoint is invalid STAC:

```shell
$ curl -s https://maxar-opendata.s3.amazonaws.com/events/catalog.json | jq '{ type: .type, stac_version: .stac_version }'
{
  "type": null,
  "stac_version": "1.0.0"
}
```

[`type` is a required field in STAC v1.0](https://github.com/radiantearth/stac-spec/blob/master/catalog-spec/catalog-spec.md#catalog-fields). STAC v0.6 [did not require the `type` field](...), so one way to open the catalog would be to change the `stac_version` attribute, e.g.:

```shell
$ curl -s https://maxar-opendata.s3.amazonaws.com/events/catalog.json | jq '.stac_version = "0.6.0"' > catalog.json && python -c "import pystac; print(pystac.read_file('catalog.json'))"
<Catalog id=maxar-opendata>
```

However, the core issue should be files w/ MAXAR, as it looks like their endpoint is not producing valid STAC.

**Comment by drwelby** [comment]
Root collection now has a "type".

**Comment by gadomski** [comment]
@drwelby needs to be `Catalog` (it's currently `catalog`).

**Comment by drwelby** [comment]
ack, should be fixed now!

**Comment by gadomski** [comment]
Looks good to me, @giswqs can you confirm the fix from your end? Thanks @drwelby!

```shell
$ python -c "import pystac; print(pystac.read_file('https://maxar-opendata.s3.amazonaws.com/events/catalog.json '))"
<Catalog id=maxar-opendata>
$ stac-validator https://maxar-opendata.s3.amazonaws.com/events/catalog.json
[
    {
        "version": "1.0.0",
        "path": "https://maxar-opendata.s3.amazonaws.com/events/catalog.json",
        "schema": [
            "https://schemas.stacspec.org/v1.0.0/catalog-spec/json-schema/catalog.json"
        ],
        "valid_stac": true,
        "asset_type": "CATALOG",
        "validation_method": "default"
    }
]
```

**Comment by giswqs** [comment]
Thank you both for the prompt response. Much appreciated. I am at a meeting. Will test it in an hour

**Comment by giswqs** [comment]
It works like a charm! Many thanks. 

@drwelby It would be awesome if it can support item search. That would make it much easier to filter the items. 

![image](https://user-images.githubusercontent.com/5016453/219138492-c5f79262-365a-40f1-8bb0-7d69b309dcd3.png)

```python
from pystac_client import Client
url = 'https://maxar-opendata.s3.amazonaws.com/events/catalog.json'
client = Client.open(url)
client.search(datetime='2023-02-01/2023-02-28')
```

> NotImplementedError: This catalog does not support search because it does not conform to "ConformanceClasses.ITEM_SEARCH"

**Comment by drwelby** [comment]
At this time we're only providing static catalogs but ingesting into a searchable STAC API would be a nice feature and is something we're considering.
